Revert "[nrf noup] boards: thingy53_nrf5340: Add common partition map"
nrfconnect/sdk-zephyr pull request #1004
Opened 2022-12-02 14:51 UTC by MarekPieta

This reverts commit 9a8680372fdb6e09f3d6537c8c6751dd5c50bf86.

2022-12-05 15:04 UTC, kapi-no approved these changes

2022-12-06 08:16 UTC, tejlmand requested changes
I don't believe we should revert, it's just more work for ourselves, if anything, this should be merged instead #994

2022-12-06 08:31 UTC, MarekPieta commented
The PR could Thingy;53 known issue from NCS 2.2.0.  Still I understand it was rejected and we need to live with the known issue.

2022-12-06 10:09 UTC, MarekPieta commented
This would not go into NCS 2.2.0. There is no point to introduce it later on. Closed.

2022-12-06 10:09 UTC, closed without merging