[nrf fromtree] net: ip: net_context: AF_PACKET/SOCK_RAW/IPPROTO_RAW: set pkt family
nrfconnect/sdk-zephyr pull request #1023
Opened 2023-01-12 08:02 UTC by jhirsi

Pull PR: https://github.com/zephyrproject-rtos/zephyr/pull/53440 into the NCS.

2023-01-12 11:15 UTC, rlubos commented
Will need a manifest update in `sdk-nrf` for this (I suggest to wait for the upmerge to finish though).

2023-01-25 08:05 UTC, rlubos approved these changes

2023-01-26 07:08 UTC, desowin approved these changes

2023-01-26 07:10 UTC, desowin requested changes
This is not fremtree! Upstream SHA is e92b067b7fdcf36032d2bfbd06c4dc20164acf83

2023-01-26 08:24 UTC, jhirsi commented
> This is not fromtree, but rather fromlist! This is merged and therefore to make it fromtree, the upstream SHA [e92b067](https://github.com/nrfconnect/sdk-zephyr/commit/e92b067b7fdcf36032d2bfbd06c4dc20164acf83) has to be used while cherry-picking.

Rebased and updated a SHA in a commit msg.

2023-01-26 08:58 UTC, desowin approved these changes

2023-01-26 11:32 UTC, merged