[nrf fromlist] net: wifi: Add support for regulatory domain configura…
nrfconnect/sdk-zephyr pull request #1024
Opened 2023-01-12 12:06 UTC by krish2718

…tion

Wi-Fi bands are regulated by a governing body depending on operating country, add support for the user to provide a country of operation as a hint to the Wi-Fi chipset.

Ideally if the chipset supports this is all handled internally, in that case "get" is useful but for testing and other usecases add a "set" as well, similar to "iw reg set" or "country_code=" configuration in hostapd/wpa_supplicant in Linux world.

This add a new offload API operation "reg_domain" that can be used to either get or set the regulatory information.

The validation is left to the underlying chipset, shell only does basic validation, (XY/00).

This is just a regulatory hint to the chipset, there could be other regulatory hints e.g., beacon that can override this configuration, so, an additional option to force this setting despite other hints is also given for testing purposes.

FYI, the standard database used is [1].

[1] - https://git.kernel.org/pub/scm/linux/kernel/git/sforshee/wireless-regdb.git/tree/db.txt

Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/53541

Signed-off-by: Krishna T <krishna.t@nordicsemi.no>

2023-01-12 12:23 UTC, rlubos approved these changes

2023-01-13 12:29 UTC, sachinthegreen approved these changes

2023-01-14 16:22 UTC, krish2718 commented
After multiple re-runs and debugging, the problem lies with `gitlint` in the compliance. Due to https://github.com/jorisroovers/gitlint/blob/main/CHANGELOG.md#v090-2017-12-03 using a single commit along with `--commits` won't work, not sure how this got missed as this was `0.9.0` but we use `0.18.0`?

So, this needs a fix.

2023-01-16 11:28 UTC, carlescufi commented
> After multiple re-runs and debugging, the problem lies with `gitlint` in the compliance. Due to https://github.com/jorisroovers/gitlint/blob/main/CHANGELOG.md#v090-2017-12-03 using a single commit along with `--commits` won't work, not sure how this got missed as this was `0.9.0` but we use `0.18.0`? @carlescufi
> 
> So, this needs a fix.

It's because we just started using this and all PRs so far had more than one commit I believe

2023-01-16 11:58 UTC, carlescufi requested changes
Please change the gitlint commit message so it amends:
`[nrf noup] ci: NCS-specific CI tweaks`

2023-01-16 12:14 UTC, krish2718 commented
Depends on #1027

2023-01-16 14:45 UTC, carlescufi approved these changes

2023-01-16 16:08 UTC, merged