net: lib: nrf_cloud: updated test-spec.yml to trigger downstream job
nrfconnect/sdk-zephyr pull request #1036
Opened 2023-01-23 20:38 UTC by tony-le-24

Added an entry for CI-cloud-test that will run the downstream job of test-fw-nrfconnect-nrf-iot_cloud when any of the listed modules change.

See IRIS-5423

Signed-off-by: Tony Le <tony.le@nordicsemi.no>

2023-01-23 20:43 UTC, glarsennordic commented
I think a special cherry picking and naming process needs to be followed for commits to this repository

See the previous commits to this file:

https://github.com/nrfconnect/sdk-zephyr/commits/main/.github/test-spec.yml

2023-01-23 20:43 UTC, glarsennordic requested changes
see prior comment

2023-01-23 21:31 UTC, glarsennordic approved these changes
LGTM

2023-01-24 18:25 UTC, plskeggs approved these changes
I suspect these are overly-broad rules, and will trigger more runs of our tests than really necessary.  But since this mostly will happen during upmerges and not day-to-day, hopefully it will be fine.

2023-01-24 18:25 UTC, plskeggs commented on .github/test-spec.yml
> +  - "drivers/net/**/*"
drivers/net seems logical to include based on the name, but we don't use any of those specific drivers

2023-01-25 21:15 UTC, shantha-14 approved these changes

2023-01-26 07:51 UTC, merged