[nrf fromlist] Bluetooth: Controller: Fix missing DF related radio register reset
nrfconnect/sdk-zephyr pull request #1044
Opened 2023-02-01 07:55 UTC by cvinayak

Fix missing DF related Radio register reset on radio_reset().

Regression in commit 465a96181d7d ("Bluetooth: Controller: Explicitly set all bits of used radio registers") due to the removal of NRF_RADIO->POWER register use that was used to reset all Radio registers on every new Radio Event.

Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/54296

Signed-off-by: Vinayak Kariappa Chettimada <vich@nordicsemi.no>

2023-02-02 10:17 UTC, aescolar commented
The zephyr PR is merged, you can make this a fromtree one.

2023-02-02 16:57 UTC, aescolar approved these changes

2023-03-02 10:02 UTC, de-nordic approved these changes

2023-03-17 15:58 UTC, jfischer-no requested changes
This commit is part of current upmerge, can this PR be closed?

2023-03-18 23:50 UTC, closed without merging