net: wifi_mgmt: Add support for power save timeout configuration
nrfconnect/sdk-zephyr pull request #1045
Opened 2023-02-02 09:58 UTC by ajayparida

Add support for configuring power save timeout in Wi-Fi chipsets. Changes to configure power save inactivity timer.

Signed-off-by: Ajay Parida <ajay.parida@nordicsemi.no>

2023-02-02 10:02 UTC, rlubos commented
The commit title should be prefixed with `[nrf fromtree] ` tag. Also, please cherry-pick with `-x` option, so that upstream commit is referenced.

2023-02-02 13:59 UTC, rlubos approved these changes

2023-02-02 13:59 UTC, rlubos commented
Looks good, but as with other `sdk-zephyr` cherry-picks, it needs an ACK from the release team.

2023-02-02 14:01 UTC, krish2718 requested changes
The cherry-pick commit in commit log looks wrong, it has to be upstream commit.

2023-02-02 14:01 UTC, krish2718 commented on subsys/net/l2/wifi/wifi_shell.c
> +		  "Configure Wi-Fi power save inactivity timer(in ms)",
Ideally the API can also be called set_ps_inactivitity, but I guess this is already merged upstream, so, lets leave it for now.

2023-02-07 07:34 UTC, krish2718 commented
> The cherry-pick commit in commit log looks wrong, it has to be upstream commit.

Looks correct, sorry.

2023-02-07 07:34 UTC, krish2718 approved these changes

2023-02-10 09:58 UTC, shantha-14 approved these changes

2023-02-14 08:57 UTC, merged