[nrf fromtree] manifest: modules: openthread: Gpio diag and Kconfig
nrfconnect/sdk-zephyr pull request #1049
Opened 2023-02-03 11:04 UTC by maciejbaczmanski

This PR adds gpio diag commands implementation for OpenThread modules and necessary helpers.

It also includes cleanup of Kconfig and CMakeLists. west manifest change was removed from cherry-picked commit.

(cherry picked from commit https://github.com/zephyrproject-rtos/zephyr/commit/874699d524f11fb9a8f5f00788a44c2303bb4ea8)
(cherry picked from commit https://github.com/zephyrproject-rtos/zephyr/commit/515c89580862107eb2f81da55e84e564be8e9da6)
(cherry picked from commit https://github.com/zephyrproject-rtos/zephyr/commit/a8fd0b31ca802b844c627b2938934ac5eaca37d3)

Signed-off-by: Maciej Baczmanski <maciej.baczmanski@nordicsemi.no>

2023-02-03 11:35 UTC, rlubos approved these changes

2023-02-03 11:53 UTC, maciejbaczmanski commented
Please do not merge untill fix: https://github.com/zephyrproject-rtos/zephyr/pull/54421 is merged and added to this PR

2023-02-06 10:45 UTC, tmon-nordic requested changes
The cherry-picked from commits do not appear in upstream zephyr repository. Therefore these should be either changed to `[nrf fromlist]` or the commit hash should be fixed.

2023-02-06 11:29 UTC, maciejbaczmanski commented
> The cherry-picked from commits do not appear in upstream zephyr repository. Therefore these should be either changed to `[nrf fromlist]` or the commit hash should be fixed.

thanks @tmon-nordic, commit hashes were incorrect. They should be fine now. 

> Please do not merge untill fix: [zephyrproject-rtos/zephyr#54421](https://github.com/zephyrproject-rtos/zephyr/pull/54421) is merged and added to this PR
PR was merged succesfully and commit's cherry pick has been added to this PR. Able to merge again

2023-02-09 06:35 UTC, tmon-nordic approved these changes

2023-02-14 14:13 UTC, merged