Add new kconfigs
nrfconnect/sdk-zephyr pull request #1095
Opened 2023-03-08 08:25 UTC by mariuszpos

2023-03-08 13:30 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| openthread | https://github.com/zephyrproject-rtos/openthread/commit/3e138d3f5d549894b79cdc8567ed1f9215281344 | 0a79c30a202cf0c96d2ce5e37ee01a0546ed40c5 | [zephyrproject-rtos/openthread@3e138d3f..0a79c30a](https://github.com/zephyrproject-rtos/openthread/compare/3e138d3f5d549894b79cdc8567ed1f9215281344..0a79c30a202cf0c96d2ce5e37ee01a0546ed40c5) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2023-03-09 08:42 UTC, canisLupus1313 commented on west.yml
> +      revision: 0a79c30a202cf0c96d2ce5e37ee01a0546ed40c5
You should drop the revision or update it to the same that we have in zephyr.

2023-04-05 10:23 UTC, jciupis requested changes
Missing sauce tags

2023-04-05 12:21 UTC, canisLupus1313 approved these changes

2023-04-05 12:31 UTC, jciupis approved these changes

2023-04-05 12:45 UTC, edmont approved these changes

2023-05-04 12:37 UTC, mariuszpos commented
Merged with: https://github.com/nrfconnect/sdk-zephyr/pull/1132

2023-05-04 12:37 UTC, closed without merging