modules: canopennode: Updated CANopenNode driver to v2.0
nrfconnect/sdk-zephyr pull request #1099
Opened 2023-03-09 18:03 UTC by alibenpeng

This commit updates the existing zephyr driver for canopennode from v1.3 to v2.0 and adds support for all new upstream driver features. The motivation for this was that I needed the ASCII gateway feature, which is not available in v1.3.
I ran checkpatch on my own code, but the stuff in the objdict-directory of the example is autogenerated and won't pass. But I hardly even touched that, so it should be fine.

2023-03-09 18:04 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| canopennode | https://github.com/zephyrproject-rtos/canopennode/commit/53d3415c14d60f8f4bfca54bfbc5d5a667d7e724 | 0c000b59242e006630fe326eb3ef5a8b78ada38f | [zephyrproject-rtos/canopennode@53d3415c..0c000b59](https://github.com/zephyrproject-rtos/canopennode/compare/53d3415c14d60f8f4bfca54bfbc5d5a667d7e724..0c000b59242e006630fe326eb3ef5a8b78ada38f) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2023-03-17 15:26 UTC, jfischer-no requested changes
What is the reason to do it for NCS?

2023-03-20 11:11 UTC, alibenpeng commented
> What is the reason to do it for NCS?

Actually I wasn't sure where to submit this. Should this go directly into upstream Zephyr?

2023-03-20 11:26 UTC, alibenpeng commented
> > > What is the reason to do it for NCS?
> > 
> > 
> > Actually I wasn't sure where to submit this. Should this go directly into upstream Zephyr?
> 
> Yes, please.

Alright, I'll close this then.

2023-03-20 11:26 UTC, closed without merging