[nrf fromlist] net: wifi: Log failure reason for AP mode
nrfconnect/sdk-zephyr pull request #1103
Opened 2023-03-23 08:37 UTC by krish2718

In case AP mode is not supported log the failure reason clearly.

Upstream-PR: https://github.com/zephyrproject-rtos/zephyr/pull/56135

2023-03-23 08:40 UTC, rado17 approved these changes

2023-03-23 09:11 UTC, sachinthegreen approved these changes

2023-03-23 21:32 UTC, jfischer-no requested changes
:dragon:

2023-03-24 07:28 UTC, krish2718 commented
> dragon

Can you please elaborate as to why changes are requested? I don't know the meaning of dragon in code (google says its used for not understood code).

2023-03-24 12:15 UTC, jfischer-no commented
> > dragon
> 
> Can you please elaborate as to why changes are requested? I don't know the meaning of dragon in code (google says its used for not understood code).

No, that is me, seeing people still ignorieng upmerge.

2023-05-15 07:31 UTC, rlubos commented
@krish2718 Is this aiming 2.4? If so, please rebase - conflict.

2023-05-15 07:41 UTC, krish2718 commented
> @krish2718 Is this aiming 2.4? If so, please rebase - conflict (same for the manifest PR).

This was already part of upmerge (1e6e20f6676ea16c93516237293d6188ce02899e), so, closing this, thanks for pointing.

2023-05-15 07:41 UTC, closed without merging