[nrf fromlist] net: context: Set priority based on DSCP
nrfconnect/sdk-zephyr pull request #1106
Opened 2023-03-27 17:10 UTC by krish2718

If a socket has DSCP set then the packets from the socket should also be marked with appropriate priority in case traffic classes are used in networking stack.

Signed-off-by: Krishna T <krishna.t@nordicsemi.no>
(cherry picked from commit 0df54dd47faf7ce0eec2d8e508d6dc31f643ff18)

2023-03-28 07:47 UTC, rado17 approved these changes

2023-03-29 06:56 UTC, sachinthegreen approved these changes

2023-03-31 09:56 UTC, jfischer-no requested changes
upmerge in progress

2023-05-16 09:23 UTC, jfischer-no approved these changes
unblock

2023-05-16 09:51 UTC, rlubos commented
@krish2718 You should update the commit here.

2023-05-16 09:52 UTC, krish2718 commented
> @krish2718 You should update the commit here.

yeah, was just waiting for any further changes upstream.

2023-05-16 09:58 UTC, rlubos approved these changes

2023-05-16 11:04 UTC, merged