[nrf fromtree] logging: Changed log template to consider default log …
nrfconnect/sdk-zephyr pull request #1115
Opened 2023-04-05 11:54 UTC by kkasperczyk-no

…level

Added using LOG_DEFAULT_LEVEL kconfig option in log module template for assigning the default log level to newly created module instance, instead of assuming always INFO level.

Signed-off-by: Kamil Kasperczyk <kamil.kasperczyk@nordicsemi.no>
(cherry picked from commit 6fe83ea810ca35ca21bc3bc460dbc0fde332a559)

2023-04-05 13:06 UTC, jfischer-no requested changes
Do you want me to cherry-pick it in https://github.com/nrfconnect/sdk-zephyr/pull/1096?

2023-04-06 05:54 UTC, kkasperczyk-no commented
> Do you want me to cherry-pick it in #1096?

Hmm, if there is no problem with that, it's always nice to have it on main branch sooner than later. However I assumed that it will not go in, until upmerge ends, as it's not a bug fix.

2023-04-06 06:01 UTC, kkasperczyk-no commented
@jfischer-no btw I don't know if sdk-nrf CI will pass on this PR, so maybe let's wait to not break upmerge PR unnecessarily.

2023-04-13 13:27 UTC, jfischer-no approved these changes

2023-04-21 08:46 UTC, closed without merging