Bluetooth: Mesh: Update default adv sets for mesh
nrfconnect/sdk-zephyr pull request #1131
Opened 2023-04-18 06:39 UTC by PavelVPV

Change default mesh configuration when running with SoftDevice Controller to get better performance.

Why it is changed this way:
- This configuration is only tested on SDC and may not give the same performance on ZLL, thus can't be set in upstream;
- `default <N> if BT_LL_SOFTDEVICE` can't be used as it won't work for nRF53 board where the controller is not present in the app core.

2023-04-18 07:28 UTC, Andrewpini approved these changes

2023-04-18 08:55 UTC, jfischer-no requested changes
I do not think that performance tuning should be part of the [nrf noup] patches.

2023-04-18 10:21 UTC, Balaklaka approved these changes

2023-04-18 12:10 UTC, PavelVPV commented
> I do not think that performance tuning should be part of the [nrf noup] patches.

The explanation is given in the commit message. We want this to be a `default` configuration for mesh in NCS. Another option is to create an overlay .conf file for all mesh samples in sdk-nrf, but this won't work for any non-sample project. So the only option I see currently is to do it this way. Please provide better suggestion if you have one.

2023-04-18 12:11 UTC, PavelVPV commented
Putting `DNM` until fix nightly CI.

2023-04-19 07:32 UTC, PavelVPV commented
Closing as found a way how to achieve this in sdk-nrf repo.

2023-04-19 07:32 UTC, closed without merging