[nrf noup] modules: mbedtls: Update PSA configuration curve names
nrfconnect/sdk-zephyr pull request #1180
Opened 2023-05-16 12:23 UTC by joerchan

fixup! [nrf noup] modules: mbedtls: add PSA configurations

Update PSA configuration curve names.
These names have many different spelling variants, use PSA names, with commonly used variants in parenthesis.

2023-05-31 09:54 UTC, vili-nordic approved these changes

2023-05-31 12:36 UTC, SebastianBoe requested changes
Why noup?

Seems like something we would either want to upstream or live with.

2023-06-01 07:02 UTC, joerchan commented
> Why noup?
> 
> Seems like something we would either want to upstream or live with.

IT's a fixup on another noup commit.

2023-06-01 07:08 UTC, SebastianBoe approved these changes

2023-07-05 10:58 UTC, vili-nordic approved these changes

2023-07-05 10:59 UTC, SebastianBoe approved these changes

2023-07-06 10:02 UTC, merged