[nrf fromtree] Bluetooth: controller: Move DF feat selection to...
nrfconnect/sdk-zephyr pull request #1189
Opened 2023-05-25 05:08 UTC by ppryga-nordic

...LL_SW_SPLIT KConfig

The BT_CTLR_DF_SUPPORTED KConfig was a wrapper for DF related features set that are supported by Zephyr's BLE Controller. At the same time the KConfig is used by Host in compound build to enable BT_DF. That makes the whole thing a bit coupled with Zephyr's controller. External implementations of controller must provide same feature set as Zephyr's Controller or there will be an error during build.

The PR moves the Zephyr's Controller DF supported features set to Kconfig.ll_sw_split, where it is included only when BT_LL_SW_SPLIT is selected. BT_CTLR_DF_SUPPORTED is now a top DF_SUPPORTED KConfig option that enables possibility to select actual DF features. That allows to select individual set of DF features by any controller implementation and makes possible to enable BT_DF and build selected DF Host features.

2023-05-25 06:35 UTC, cvinayak requested changes
Use `git cherry-pick -xs <upstream commit>` so that the hash is mentioned in the commit message as "(cherry picked from commit ...) and it is signed-off.

2023-05-25 10:02 UTC, ppryga-nordic commented
> Use `git cherry-pick -xs <upstream commit>` so that the hash is mentioned in the commit message as "(cherry picked from commit ...) and it is signed-off.

Done

2023-05-29 01:37 UTC, cvinayak approved these changes

2023-06-03 18:17 UTC, ppryga-nordic commented
@carlescufi or @kruithofa can you approve the PR? It passed build in sdk-nrf: https://github.com/nrfconnect/sdk-nrf/pull/11259

2023-06-05 07:14 UTC, kruithofa approved these changes

2023-06-05 07:31 UTC, merged