Fromtree coap client
nrfconnect/sdk-zephyr pull request #1195
Opened 2023-05-30 08:36 UTC by jarlamsa

NOT FOR RELEASE

### Description
CoAP client from upstream Zephyr.
Bringing it to `sdk-zephyr` to enable testing efforts earlier.

2023-05-30 08:44 UTC, juhaylinen approved these changes

2023-05-30 08:54 UTC, SeppoTakalo commented
Create a west.yaml PR into `nrf` repository as well.

2023-06-06 09:27 UTC, rlubos requested changes
The commits are missing a reference to the original commit (i. e. not cherry-picked with the `-x` option), see:
https://nordicsemi.atlassian.net/wiki/spaces/NCS/pages/108201225/Pull+Requests#PullRequests-Cherry-pickingcommitsintoOSSrepositoryforks

2023-06-06 09:49 UTC, jarlamsa commented
Thanks @rlubos for your review, I fixed the commits and cherry-picked again with -x.

2023-06-06 10:04 UTC, rlubos approved these changes

2023-06-06 10:04 UTC, merged