MCUmgr and SMP Client support
nrfconnect/sdk-zephyr pull request #1258
Opened 2023-07-28 10:01 UTC by jheiskan81

MCUmgr client

MCUmgr client basic implementation for support Image and OS group commands.

Image Group:

- Image state read/write
- Image Upload secondary slot
- Image Erase secondary slot

OS group:

- Reset
- Echo service

Operation's are blocked call and can't call inside worker queue.
IMG and OS needs SMP client object for transport.
SMP update

SMP client:

- SMP buffer allocation
- SMP object init for selected SMP transport
- SMP client support for generate request and handling response message.

SMP transport:

Updated SMP transport for trigger client packets.
API for register SMP transport object.
Unit test

Unit test for MCUmgr & SMP client.

2023-07-28 10:58 UTC, nordicjm requested changes
`fromtree` commits need to be cherry-picked with the `-x` argument to include the commit they came from.
Also needs a sdk-nrf manifest update to run CI too

2023-07-28 11:59 UTC, jheiskan81 commented
> `fromtree` commits need to be cherry-picked with the `-x` argument to include the commit they came from. Also needs a sdk-nrf manifest update to run CI too

Ok. Now Manifest PR trig CI and commits are cherry-picked properly.

2023-07-28 12:00 UTC, carlescufi requested changes
Blocking this until I've figured out what's wrong with CI

2023-07-28 13:51 UTC, carlescufi approved these changes

2023-07-31 11:14 UTC, nordicjm approved these changes

2023-07-31 11:50 UTC, de-nordic approved these changes

2023-07-31 15:03 UTC, merged