kernel: cherry-pick custom boot banner and set to nRF connect SDK
nrfconnect/sdk-zephyr pull request #1265
Opened 2023-08-04 08:33 UTC by nordicjm

[nrf fromtree] kernel: Add support to override banner
    
    This is useful for Zephyr customers to put their custom banners.

    [nrf noup] kernel: Set boot banner to NCS
    
    Updates the boot banner to show that it is booting nRF Connect
    SDK instead of Zephyr OS.

This looks like the following:
```
*** Booting nRF Connect SDK build v3.3.99-ncs1-2860-gb75c68264f49 ***
Hello World! nrf52840dk_nrf52840
```

Which shows the sdk-zephyr version, not the sdk-nrf version.

2023-08-04 09:25 UTC, krish2718 approved these changes

2023-08-04 12:37 UTC, tejlmand requested changes
Do we really need a `[nrf noup]` patch for this ?

2023-08-04 12:37 UTC, tejlmand commented on kernel/Kconfig
> +	default "Booting nRF Connect SDK"
does this need to be a `noup`, can't we place the default overwrite in sdf-nrf here: https://github.com/nrfconnect/sdk-nrf/blob/main/Kconfig.nrf ?

2023-08-07 07:32 UTC, nordicjm reviewed
@tejlmand this just does not work at all, BUILD_VERSION is always set even though it's not a custom build version, the original way worked

2023-08-07 10:22 UTC, tejlmand approved these changes
> @tejlmand this just does not work at all, BUILD_VERSION is always set even though it's not a custom build version, the original way worked

yes, I see with the changes to `banner.c` in ba9359d605162a492cb2f2bd8533b6a51a32aa67 we need a `noup` patch.

But when I made this comment: https://github.com/nrfconnect/sdk-zephyr/pull/1265#discussion_r1284370248, there was only a Kconfig change and no changes to `banner.c`, ref old commit: cfaa7524c0f32538ac89ad0d0bdae272f2708b96.

Approved.

2023-08-08 08:37 UTC, tejlmand requested changes
temp block for extra testing

2023-08-21 11:52 UTC, tejlmand approved these changes
approved, but technically the 2nd commit should be a `[nrf fromtree]` now because upstream PR has been merged.

https://github.com/zephyrproject-rtos/zephyr/pull/61635

2023-09-07 12:27 UTC, merged