Import some documentation infrastructure changes from upstream
nrfconnect/sdk-zephyr pull request #1266
Opened 2023-08-04 11:02 UTC by gmarull

So we are prepared for the next upmerge, and, improve user experience (docleaf + --keep-going option)

2023-08-08 12:57 UTC, nordicjm requested changes
NACKing due to license question reported upstream

2023-08-11 08:18 UTC, gmarull commented
@nordicjm docleaf stuff dropped

2023-08-11 08:51 UTC, nordicjm approved these changes

2023-08-11 09:54 UTC, gautesl approved these changes

2023-08-11 10:08 UTC, umapraseeda approved these changes

2023-08-11 10:29 UTC, merged