[nrf noup] ci: Allow non-github upstream PRs
nrfconnect/sdk-zephyr pull request #1351
Opened 2023-10-11 17:30 UTC by krish2718

fixup! [nrf noup] ci: NCS-specific CI tweaks

OSS projects still use mailing-lists, so, using a URL for patchwork or a mailing should be allowed instead of failing.

The regex is made too wide intentionally to allow all sorts, even the http URLs.

2023-10-11 17:30 UTC, krish2718 commented
I don't think this needs a manifest update, but let me know if I need to raise one.

2023-10-12 08:05 UTC, sachinthegreen approved these changes

2023-10-16 08:16 UTC, carlescufi commented
> I don't think this needs a manifest update, but let me know if I need to raise one.

It does not.

2023-10-16 08:20 UTC, carlescufi requested changes
This is Zephyr, there will always be a PR in a `fromlist` patch.

2023-10-16 08:22 UTC, carlescufi commented
Closing

2023-10-16 08:22 UTC, closed without merging