Cherry-pick latest 802.15.4 development
nrfconnect/sdk-zephyr pull request #1412
Opened 2023-12-04 12:01 UTC by jciupis

2023-12-04 12:02 UTC, canisLupus1313 approved these changes

2023-12-04 12:10 UTC, rlubos approved these changes

2023-12-13 09:45 UTC, anangl requested changes
In fc02a2e08c4ea44814674b90e187a68a502489ec:
> (cherry picked from commit f911a12110b4dd203050b6de25941200ee37d4fb)
This is not a valid upstream commit SHA (it is the one from your fork), use 29d027a47b8cb8bccfbed32f1f98e3d4d1ebe114 instead.

2023-12-13 09:51 UTC, jciupis commented
> In [fc02a2e](https://github.com/nrfconnect/sdk-zephyr/commit/fc02a2e08c4ea44814674b90e187a68a502489ec):
> 
> > (cherry picked from commit f911a12110b4dd203050b6de25941200ee37d4fb)
> 
> This is not a valid upstream commit SHA (it is the one from your fork), use [29d027a](https://github.com/nrfconnect/sdk-zephyr/commit/29d027a47b8cb8bccfbed32f1f98e3d4d1ebe114) instead.

Wow, thanks for catching that. It's fixed now.

2023-12-13 09:53 UTC, anangl approved these changes

2023-12-14 09:44 UTC, merged