Modify filter for spi_flash sample
nrfconnect/sdk-zephyr pull request #1421
Opened 2023-12-11 09:56 UTC by awojasinski-nordicsemi

Before that change the sample was filtered out by the Twister

2023-12-13 07:57 UTC, nordic-piks approved these changes

2023-12-13 09:10 UTC, anangl requested changes
SHAs in commit messages are wrong. It looks like you have cherry-picked commits from your PR, not from Zephyr main. Use the following ones: 23964234ac7e495108b2822d5627cf6e2288c48f, 8fdb8004dd0a81a171637c72d3d9fa880a88548b, and 7b78393b07a61cc5491ba0b8fc4e45b6b1414a18, respectively.

2023-12-13 19:28 UTC, awojasinski-nordicsemi commented
> SHAs in commit messages are wrong. It looks like you have cherry-picked commits from your PR, not from Zephyr main. Use the following ones: [2396423](https://github.com/nrfconnect/sdk-zephyr/commit/23964234ac7e495108b2822d5627cf6e2288c48f), [8fdb800](https://github.com/nrfconnect/sdk-zephyr/commit/8fdb8004dd0a81a171637c72d3d9fa880a88548b), and [7b78393](https://github.com/nrfconnect/sdk-zephyr/commit/7b78393b07a61cc5491ba0b8fc4e45b6b1414a18), respectively.

@anangl done

2023-12-14 10:33 UTC, awojasinski-nordicsemi commented
CI is green https://github.com/nrfconnect/sdk-nrf/pull/13392

2023-12-14 10:36 UTC, anangl approved these changes

2023-12-14 11:08 UTC, merged