[nrf fromlist] net: mgmt: Provide Regulatory channel info
nrfconnect/sdk-zephyr pull request #1432
Opened 2024-01-08 08:05 UTC by ajayparida

Updated to provide regulatory channel information along with country code.

Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/67294

2024-01-10 12:43 UTC, sachinthegreen requested changes

2024-01-10 12:43 UTC, sachinthegreen commented on include/zephyr/net/wifi_mgmt.h
> +	/** center frequency in MHz */
```suggestion
	/** Center frequency in MHz */
```

2024-01-10 12:43 UTC, sachinthegreen commented on include/zephyr/net/wifi_mgmt.h
> +	/** maximum transmission power (in dBm) */
```suggestion
	/** Maximum transmission power (in dBm) */
```

2024-01-11 07:52 UTC, sachinthegreen approved these changes

2024-01-15 08:49 UTC, jukkar approved these changes

2024-01-16 08:17 UTC, krish2718 approved these changes

2024-01-16 09:56 UTC, merged