[nrf fromlist] net: mgmt: Update app of TWT teardown status
nrfconnect/sdk-zephyr pull request #1437
Opened 2024-01-11 09:06 UTC by ajayparida

Update user/app status of TWT teardown sessions.

Upstream PR https://github.com/zephyrproject-rtos/zephyr/pull/67469

2024-01-16 08:14 UTC, krish2718 approved these changes

2024-01-16 13:06 UTC, sachinthegreen requested changes

2024-01-16 13:06 UTC, sachinthegreen commented on subsys/net/l2/wifi/wifi_shell.c
> +			print(context.sh, SHELL_NORMAL, "TWT teardown received for flow ID %d\n",
```suggestion
			print(context.sh, SHELL_NORMAL, "TWT teardown succeeded for flow ID %d\n",
```

2024-01-18 10:16 UTC, rado17 approved these changes

2024-01-19 07:23 UTC, sachinthegreen approved these changes

2024-01-24 04:39 UTC, merged