[nrf fromtree] manifest: Update nrf hw models to latest including UBSAN fixes
nrfconnect/sdk-zephyr pull request #1484
Opened 2024-02-08 16:19 UTC by ivaniushkov

* Update the HW models module to 52d0b4b7b7431d8da6222cc3b17a8afdcb099baf

Including the following:
* 52d0b4b UART: FIFO backend: Do not error out if other side disconnects Rx
* 3582b68 UART: FIFO backend: Avoid possible race
* 414f160 AAR: Fix UBSAN warnings
* 24f5d3d PPI: Fix UBSAN warning

2024-02-08 16:21 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| nrf_hw_models | https://github.com/zephyrproject-rtos/nrf_hw_models/commit/9b985ea6bc237b6ae06f48eb228f2ac7f6e3b96b | https://github.com/zephyrproject-rtos/nrf_hw_models/commit/52d0b4b7b7431d8da6222cc3b17a8afdcb099baf (main) | [zephyrproject-rtos/nrf_hw_models@9b985ea6..52d0b4b7](https://github.com/zephyrproject-rtos/nrf_hw_models/compare/9b985ea6bc237b6ae06f48eb228f2ac7f6e3b96b..52d0b4b7b7431d8da6222cc3b17a8afdcb099baf) |
| open-amp | https://github.com/zephyrproject-rtos/open-amp/commit/214f9fc1539f8e5937c0474cb6ee29b6dcb2d4b8 | https://github.com/zephyrproject-rtos/open-amp/commit/da78aea63159771956fe0c9263f2e6985b66e9d5 (master) | [zephyrproject-rtos/open-amp@214f9fc1..da78aea6](https://github.com/zephyrproject-rtos/open-amp/compare/214f9fc1539f8e5937c0474cb6ee29b6dcb2d4b8..da78aea63159771956fe0c9263f2e6985b66e9d5) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2024-02-09 09:38 UTC, aescolar approved these changes

2024-02-09 09:42 UTC, aescolar requested changes
Please do a cherry-pick from Zephyr with -x (so the "cherry-picked from" line is there)
And pick all commits, do not squash them together.

85d3ad11179cdc4bf030659e1d413215f1c6b866
992c04c471edc0ea63a4f572cf72b2195ef6a99b
33d4b6d1482c7ba2cf97a037b2a8dde260547379
c9d489d38b0cd25f35d5e33c03144c90204600d0
189d4d4b069d78de1f17b4179229ca00d4d80789

2024-02-09 09:49 UTC, aescolar approved these changes

2024-02-10 13:21 UTC, ivaniushkov commented
CI in manifest PR is green:
https://github.com/nrfconnect/sdk-nrf/pull/13934

2024-02-12 08:52 UTC, aescolar approved these changes

2024-02-12 11:34 UTC, ilhanates reviewed
Can u point me a test-ble build to verify changes?
I could not see it here https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13934/

2024-02-12 14:21 UTC, ilhanates approved these changes

2024-02-12 14:27 UTC, merged