[manifest] update tinycrypt revision
nrfconnect/sdk-zephyr pull request #1509
Opened 2024-02-16 15:40 UTC by ivaniushkov

update tinycrypt revision to fix
warnings reported by ubsan

2024-02-16 15:41 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| tinycrypt | https://github.com/zephyrproject-rtos/tinycrypt/commit/3e9a49d2672ec01435ffbf0d788db6d95ef28de0 (master) | https://github.com/zephyrproject-rtos/tinycrypt/pull/3 | [zephyrproject-rtos/tinycrypt#3/files](https://github.com/zephyrproject-rtos/tinycrypt/pull/3/files) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2024-02-16 16:03 UTC, gmarull requested changes
please update the PR upstream first

2024-02-19 14:14 UTC, ivaniushkov commented
will update the PR after NCS2.6 release

2024-03-07 19:40 UTC, gmarull approved these changes

2024-03-13 08:54 UTC, Tschet1 approved these changes

2024-03-14 08:07 UTC, merged