test-spec: descope samples and tests from many CIs
nrfconnect/sdk-zephyr pull request #1513
Opened 2024-02-19 12:06 UTC by guwa

Descope samples and tests from many CIs, since the majority are not affecting the functionality of protocols and applications.
Samples that may affect the overall performance and functionality, should be enabled specifically.

2024-02-19 13:03 UTC, dawidprzybylo requested changes

2024-02-19 14:19 UTC, rugeGerritsen commented on .github/test-spec.yml
> -  - "**/*"
Is it intentional to run the FEM CI when only files in the /test folder have changed?

2024-02-20 06:41 UTC, dawidprzybylo approved these changes

2024-02-20 06:41 UTC, dawidprzybylo commented on .github/test-spec.yml
> -  - "**/*"
Discusses with @guwa  that bluetooth paths can be excluded in FEM/RS

2024-02-20 09:26 UTC, thst-nordic approved these changes

2024-02-20 13:33 UTC, MarekPieta approved these changes

2024-02-20 13:33 UTC, MarekPieta commented on .github/test-spec.yml
> +      - "!tests/bluetooth/**/*"
Maybe even `!samples/**/*` and `!tests/**/*`? These integration test suite is only for `applications/nrf_desktop` from nRF Connect SDK and changes to samples/tests should not affect it.

2024-02-20 17:05 UTC, merged