[nrf fromlist] kconfig: shell: increase shell stack size for OpenThread
nrfconnect/sdk-zephyr pull request #1560
Opened 2024-03-05 11:11 UTC by maciejbaczmanski

Shell stack size is too low for OpenThread without joiner functionality, causing overflow. This commit increases it.

upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/69783

Signed-off-by: Maciej Baczmanski <maciej.baczmanski@nordicsemi.no>
(cherry picked from commit 4fb493e49fef245e62df21620382e027a7200907)

2024-03-05 11:11 UTC, canisLupus1313 approved these changes

2024-03-05 11:17 UTC, edmont approved these changes

2024-03-05 17:08 UTC, jfischer-no requested changes
Does it fix stack size for NCS or native Zephyr?

2024-03-05 17:27 UTC, maciejbaczmanski commented
> Does it fix stack size for NCS or native Zephyr?

For NCS. Currently shell stack size is too small for some variants causing overflow on openthread samples

2024-03-06 07:15 UTC, LuDuda approved these changes

2024-03-06 08:56 UTC, maciejbaczmanski commented
> > > Does it fix stack size for NCS or native Zephyr?
> > 
> > 
> > For NCS. Currently shell stack size is too small for some variants causing overflow on openthread samples
> 
> Then it is better to resolve it in NCS not in Zephyr, maybe like other application and samples in NCS do it. How many releases will the stack be sufficient and we see another fromlist patch?

This is a bugfix. As it can be seen in changed file, value of stack size is not changed. Incorrect assigning of value for opentrhead with no joiner functionality has been removed. PR has been approved upstream. Resolving it in NCS would only cause doubling of configs with the same value.

2024-03-06 09:24 UTC, jfischer-no commented
Your commit message: "Shell stack size is too low for OpenThread without joiner
functionality, causing overflow. This commit increases it."

>As it can be seen in changed file, value of stack size is not changed. Incorrect assigning of value for opentrhead with no joiner functionality has been removed. 

Is it just me who sees two different statements?

> Resolving it in NCS would only cause doubling of configs with the same value.

But you answer to my question "Does it fix stack size for NCS or native Zephyr?" is "For NCS.". According to you answer this value does not applies to native Zephyr RTOS but to NCS only, therefore is should be fixed in NCS.

Also changed here: https://github.com/nrfconnect/sdk-zephyr/pull/366/commits/4b94355440861c1973a6f976cc46760d4bfc77db

2024-03-06 11:05 UTC, carlescufi commented
> > > > Does it fix stack size for NCS or native Zephyr?
> > > 
> > > 
> > > For NCS. Currently shell stack size is too small for some variants causing overflow on openthread samples
> > 
> > 
> > Then it is better to resolve it in NCS not in Zephyr, maybe like other application and samples in NCS do it. How many releases will the stack be sufficient and we see another fromlist patch?
> 
> This is a bugfix. As it can be seen in changed file, value of stack size is not changed. Incorrect assigning of value for opentrhead with no joiner functionality has been removed. PR has been approved upstream. Resolving it in NCS would only cause doubling of configs with the same value.

I discussed with @maciejbaczmanski and we agreed that this does apply upstream. The commit message will be amended.

2024-03-06 11:08 UTC, SeppoTakalo approved these changes

2024-03-06 11:34 UTC, jfischer-no commented
> I discussed with @maciejbaczmanski and we agreed that this does apply upstream. The commit message will be amended.

okay. I will merged it asap depending on rebase process.

2024-03-07 07:49 UTC, merged