[nrf fromlist] boards: nrf54h20dk: Enable shell input
nrfconnect/sdk-zephyr pull request #1635
Opened 2024-04-15 13:59 UTC by krish2718

This enables typing commands in shell over UART.

Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/71498 (Backport to HWMv1)

2024-04-15 13:59 UTC, krish2718 commented
Manually backported to HWMv1, hope the oss-history will pass or we can override, as upmerge is pulling in HWMv2.

2024-04-19 16:16 UTC, krish2718 commented
@KAGA164 trying to cherry-pick my commit `c091c944b6c` is now showing conflicts because of difference in order b/w downstream and 
upstream, any ideas on how to handle this? Doing a revert to apply in proper order also causes conflicts. Used `board: nrf54h20dk: Add missing default BT related configs` as a common ref.

Upstream order: `boards/nordic/nrf54h20dk/`

```
b2890564e9c boards: nordic: nrf54h20dk: Add configuration for BLE
27737924905 boards: nordic: nrf54h20dk: Change IPC default backend
711abcd4442 boards: nordic: nrf54h20dk: Add IPC configuration for SysCtrl
c091c944b6c boards: nrf54h20dk: Enable shell input
c7c6cb4c99b boards: nordic: nrf54h20dk: enable HWFC
abca9170553 boards: board dts and defconfig file adjustments
006ea0f6fba boards: Split merged board file configuration up
6f07cecc952 boards: nrf54h20: Fix storage partitions for setting subsytem
b0f9391aee3 board: nrf54h20dk: Add missing default BT related configs
```
Downstream order: `boards/arm/nrf54h20dk_nrf54h20/`
```
dd3931ad85d [nrf fromlist] boards: nordic: nrf54h20dk: Add configuration for BLE
2f52b92ebdd [nrf fromlist] boards: nordic: nrf54h20dk: Change IPC default backend
dd8fd472657 [nrf fromlist] boards: nordic: nrf54h20dk: enable HWFC
c976657eb74 [nrf noup] entropy: Add fake entropy nRF PRNG driver
a503870a7a7 [nrf fromtree] board: nrf54h20dk: Add missing default BT related configs
```

2024-04-22 08:14 UTC, KAGA164 commented
> @KAGA164 trying to cherry-pick my commit `c091c944b6c` is now showing conflicts because of difference in order b/w downstream and upstream, any ideas on how to handle this? Doing a revert to apply in proper order also causes conflicts. Used `board: nrf54h20dk: Add missing default BT related configs` as a common ref.
> 
> Upstream order: `boards/nordic/nrf54h20dk/`
> 
> ```
> b2890564e9c boards: nordic: nrf54h20dk: Add configuration for BLE
> 27737924905 boards: nordic: nrf54h20dk: Change IPC default backend
> 711abcd4442 boards: nordic: nrf54h20dk: Add IPC configuration for SysCtrl
> c091c944b6c boards: nrf54h20dk: Enable shell input
> c7c6cb4c99b boards: nordic: nrf54h20dk: enable HWFC
> abca9170553 boards: board dts and defconfig file adjustments
> 006ea0f6fba boards: Split merged board file configuration up
> 6f07cecc952 boards: nrf54h20: Fix storage partitions for setting subsytem
> b0f9391aee3 board: nrf54h20dk: Add missing default BT related configs
> ```
> 
> Downstream order: `boards/arm/nrf54h20dk_nrf54h20/`
> 
> ```
> dd3931ad85d [nrf fromlist] boards: nordic: nrf54h20dk: Add configuration for BLE
> 2f52b92ebdd [nrf fromlist] boards: nordic: nrf54h20dk: Change IPC default backend
> dd8fd472657 [nrf fromlist] boards: nordic: nrf54h20dk: enable HWFC
> c976657eb74 [nrf noup] entropy: Add fake entropy nRF PRNG driver
> a503870a7a7 [nrf fromtree] board: nrf54h20dk: Add missing default BT related configs
> ```

@krish2718 It seems like you have been managed to resolve conflict?

2024-04-22 08:17 UTC, krish2718 commented
> @krish2718 It seems like you have been managed to resolve conflict?

No, as we aren't supposed to manually resolve conflicts, and cherrypick/revert is throwing conflicts, I don't have a solution.

2024-04-25 13:49 UTC, gmarull commented
needs approvals

2024-04-25 13:53 UTC, anangl approved these changes

2024-04-26 10:22 UTC, KAGA164 approved these changes

2024-05-03 12:07 UTC, nordicjm requested changes
this PR doesn't even make sense

2024-05-03 16:30 UTC, krish2718 commented
Already merged as part of upmerge.

2024-05-03 16:30 UTC, closed without merging