[nrf noup] Bluetooth: Mesh: Disable processing of ext ADV packets
nrfconnect/sdk-zephyr pull request #1730
Opened 2024-05-21 13:42 UTC by Balaklaka

Disable processing of extended ADV packets by mesh scanner. This is done to prevent loss of scan time due to reception of pointer packets while scanning for mesh packets.

2024-05-21 16:55 UTC, mia-ko requested changes
Do we need a changelog entry?

2024-05-21 16:55 UTC, mia-ko commented on subsys/bluetooth/mesh/Kconfig
> +	  advertising packets. This is default set to false, to prevent loss of
```suggestion
	  advertising packets. This is set to false by default, to prevent loss of
```

2024-05-21 16:55 UTC, mia-ko commented on subsys/bluetooth/mesh/Kconfig
> +	  scan time due to reception of pointer packet while scanning for mesh
```suggestion
	  scan time due to reception of a pointer packet while scanning for mesh
```

2024-05-22 07:15 UTC, alxelax requested changes

2024-05-22 09:10 UTC, Balaklaka commented
> Do we need a changelog entry?

No, we do not want a changelog entry.

2024-05-22 09:26 UTC, mia-ko requested changes

2024-05-22 09:26 UTC, mia-ko commented on subsys/bluetooth/mesh/Kconfig
> +	  packet while scanning for mesh packets. Need to be set to true if
```suggestion
	  packet while scanning for mesh packets. Set it to true if
```

2024-05-22 09:26 UTC, mia-ko commented on subsys/bluetooth/mesh/Kconfig
> +	  Controller for other purposes than mesh.
Can we say just mesh here, or should it be Bluetooth Mesh?

2024-05-22 10:47 UTC, mia-ko approved these changes

2024-05-22 13:36 UTC, alxelax approved these changes

2024-05-27 12:34 UTC, omkar3141 requested changes

2024-05-28 08:17 UTC, omkar3141 approved these changes

2024-06-03 14:57 UTC, merged