[nrf fromlist] usb: device_next: hid: fix Get Report buffer handling
nrfconnect/sdk-zephyr pull request #1762
Opened 2024-06-03 09:52 UTC by MarekPieta

After the get_report() callback, we need to determine how many bytes the HID device wrote to the report buffer. Use the callback return value to do this, and modify the net_buf data length value if get_report was successful.

Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/73467

Reported-by: Marek Pieta <Marek.Pieta@nordicsemi.no>
Signed-off-by: Johann Fischer <johann.fischer@nordicsemi.no>

2024-06-03 10:05 UTC, jfischer-no approved these changes

2024-06-03 10:18 UTC, tmon-nordic approved these changes

2024-06-03 13:06 UTC, tmon-nordic requested changes
Blocking until [73657](https://github.com/zephyrproject-rtos/zephyr/pull/73657) is reviewed upstream by Johann.

2024-06-03 13:27 UTC, tmon-nordic approved these changes

2024-06-04 08:12 UTC, tmon-nordic requested changes
You changed the title to Cherry-pick USB next fixes. Could you please then cherry-pick also the other that are already merged PRs (73255, 73142, 73561, 73463)?

2024-06-04 08:58 UTC, MarekPieta commented
Hi @tmon-nordic,
I did the requested cherry-pick. Please rereview

2024-06-04 11:00 UTC, tmon-nordic approved these changes

2024-06-04 13:32 UTC, merged