[nrf noup] scripts: west_commands: build: Add NCS example repo to sys…
nrfconnect/sdk-zephyr pull request #1778
Opened 2024-06-06 09:53 UTC by nordicjm

…build list

Adds the example NCS project to the list of repos that should build using sysbuild by default

2024-06-11 13:39 UTC, tejlmand commented on scripts/west_commands/build.py
> +                           'hal_nordic', 'ncs-example-application.git' ]
why the `.git` ?

```suggestion
                           'hal_nordic', 'ncs-example-application' ]
```

2024-06-11 13:41 UTC, carlescufi requested changes
squash with an earlier noup?

2024-06-11 13:48 UTC, carlescufi approved these changes

2024-06-12 08:41 UTC, 57300 approved these changes

2024-06-12 08:54 UTC, tejlmand approved these changes

2024-06-12 12:36 UTC, merged