[nrf noup] samples: sysbuild: hello_world: support PM on nRF53
nrfconnect/sdk-zephyr pull request #1802
Opened 2024-06-12 14:16 UTC by gmarull

PM support is still required for nRF53 in the context of NCS.

2024-06-12 15:42 UTC, AliNordic approved these changes

2024-06-13 06:23 UTC, nordicjm requested changes

2024-06-13 06:23 UTC, nordicjm commented on samples/sysbuild/hello_world/sysbuild.cmake
> +if("${SB_CONFIG_REMOTE_BOARD}" STREQUAL "nrf5340dk/nrf5340/cpunet")
```suggestion
if(SB_CONFIG_SOC_SERIES_NRF53X)
```

2024-06-13 08:19 UTC, nordicjm approved these changes

2024-06-13 11:24 UTC, merged