[nrf noup] bluetooth: att: Allow ATT sent callback after data TX is done
nrfconnect/sdk-zephyr pull request #1819
Opened 2024-06-14 13:29 UTC by MarekPieta

By default, the BLE stack calls sent callback for ATT data when the data is passed to BLE controller for transmission. Enabling this Kconfig option delays calling the sent callback until data transmission is finished by BLE controller (the callback is delayed until receiving the num complete packets event).

PR also allows for an extra ref in bt_conn_send_cb.

Jira: NCSDK-27422

2024-06-14 13:47 UTC, MarekPieta commented
After discussion with @rugeGerritsen, I started to wonder if we should mark this feature as experimental/deprecated (it's a temporary fix that would be removed in one of the following NCS releases). On the other hand introducing a new feature as deprecated without providing an alternative solution may not be a good idea. An application that is going to use the workaround (nRF Desktop) has production quality since some time already, so enabling an experimental feature for all of the peripheral configurations there is also controversial.

Please let me know what's your opinion on this.

2024-06-14 17:51 UTC, tejlmand commented
Why is this a `[nrf noup]` ?

Can't this be written in a way which is beneficial for upstream.

2024-06-17 06:48 UTC, jori-nordic commented
> Can't this be written in a way which is beneficial for upstream

This is re-introducing coupling between the host and the controller that we're trying to remove upstream.
Having it [noup] allows us to patch the issue for the impeding release, while giving us some time to design a better way without the time pressure.

2024-06-17 06:54 UTC, jori-nordic requested changes
there is an assert you also have to tweak.
See the bsim run in the upstream PR you opened.

2024-06-17 10:12 UTC, tejlmand commented
> Having it [noup] allows us to patch the issue for the impeding release, while giving us some time to design a better way without the time pressure.

thanks for the explanation.

2024-06-18 10:23 UTC, kapi-no approved these changes

2024-06-18 10:23 UTC, kapi-no commented on subsys/bluetooth/host/Kconfig.gatt
> +	  upon receiving the num complete packets event).
The event is called

```suggestion
	  upon receiving the Number of Completed Packets HCI Event).
```

2024-06-18 10:25 UTC, mkapala-nordic approved these changes

2024-06-18 10:25 UTC, carlescufi requested changes
Why is this a noup?

2024-06-18 10:40 UTC, carlescufi approved these changes
Technical debt tracked here:
https://nordicsemi.atlassian.net/plugins/servlet/mobile?originPath=%2Fbrowse%2FNCSDK-28016#issue/NCSDK-28016

2024-06-18 10:54 UTC, theob-pro approved these changes

2024-06-18 10:55 UTC, kapi-no approved these changes

2024-06-18 13:43 UTC, merged