Changes required for emulated peripherals on L15
nrfconnect/sdk-zephyr pull request #1887
Opened 2024-07-12 10:29 UTC by masz-nordic

2024-07-12 10:35 UTC, 57300 approved these changes

2024-07-12 13:00 UTC, jaz1-nordic approved these changes

2024-07-16 08:40 UTC, nordic-segl approved these changes

2024-07-18 07:17 UTC, nordic-piks requested changes
There is a lot of code added into driver/mbox and code changed in subsys/ipc/ipc_service.
There are needed tests/samples to cover those changes.

2024-07-19 12:28 UTC, nordic-piks approved these changes

2024-07-29 11:06 UTC, merged