samples: basic: blinky: add mbox backend for eGPIO
nrfconnect/sdk-zephyr pull request #1910
Opened 2024-07-24 09:34 UTC by jaz1-nordic

PR based on #1887. Only last commit is related to this PR.

2024-07-25 05:18 UTC, nordic-piks commented on samples/basic/blinky/sample.yaml
> +    harness: led
There is no such harness `led`, it is dummy one.
Please change to `console` and add expected regex from sample.

2024-07-25 05:21 UTC, nordic-piks commented on samples/basic/blinky/sample.yaml
> +    harness: led
You can do sth similar to this:
https://github.com/zephyrproject-rtos/zephyr/pull/72730/files

2024-07-25 05:22 UTC, nordic-piks requested changes
Please allow verification via console logs for blinky sample.

2024-09-03 11:46 UTC, nordic-piks commented on samples/basic/blinky/sample.yaml
> +      - nrf54l15pdk/nrf54l15/cpuapp
Can you add DK target too?

2024-09-03 11:47 UTC, nordic-piks commented on samples/basic/blinky/sample.yaml
> +      - nrf54l15pdk/nrf54l15/cpuapp
Can you add DK target too?

2024-09-09 13:54 UTC, nordic-piks approved these changes

2024-09-09 13:58 UTC, masz-nordic commented on samples/basic/blinky/sysbuild.conf
> +SB_CONFIG_PARTITION_MANAGER=n
This could be moved to `sample.yaml` to limit impact.

2024-09-13 09:00 UTC, magp-nordic approved these changes

2024-09-13 09:26 UTC, masz-nordic approved these changes

2024-09-17 14:44 UTC, magp-nordic approved these changes

2024-09-18 06:09 UTC, nordic-segl approved these changes

2024-09-26 08:53 UTC, carlescufi submitted a review, later dismissed
why is this a noup instead of a fromlist?

2024-09-26 08:55 UTC, gmarull reviewed
I don't think we should be carrying these sort of patches downstream. They do not seem to follow best practices, and will likely keep increasing upmerge times. Why isn't this developed directly upstream?

2024-09-26 09:25 UTC, carlescufi commented
Please use the alt-root instead: https://github.com/nrfconnect/sdk-nrf/tree/main/scripts/twister/alt/zephyr
Check with @PerMac for additional info about the twister alt-root we have in Zephyr.

2024-10-02 06:29 UTC, merged