nRF54l20 soc and board
nrfconnect/sdk-zephyr pull request #1917
Opened 2024-07-29 13:01 UTC by kl-cruz

Add device and board descriptions.

2024-07-29 13:02 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| hal_nordic | https://github.com/zephyrproject-rtos/hal_nordic/commit/ab5cb2e2faeb1edfad7a25286dcb513929ae55da | https://github.com/zephyrproject-rtos/hal_nordic/pull/200 | [zephyrproject-rtos/hal_nordic#200/files](https://github.com/zephyrproject-rtos/hal_nordic/pull/200/files) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2024-07-29 13:14 UTC, hubertmis approved these changes

2024-07-29 13:14 UTC, hubertmis commented on boards/nordic/nrf54l20pdk/Kconfig
> +# nRF54L15 PDK board configuration
typo: 54L20

2024-07-29 13:14 UTC, hubertmis commented on dts/common/nordic/nrf54l20.dtsi
> +#define NRF_DOMAIN_ID_APPLICATION 0
There is no IPCT in nRF54L20. Is there?

2024-08-02 09:40 UTC, e-rk approved these changes

2024-08-02 14:12 UTC, anangl requested changes
- commit "[nrf fromlist] manifest: Update hal_nordic with nrfx 3.6" is invalid; there is no such commit in https://github.com/zephyrproject-rtos/zephyr/pull/76332. Instead, commits from https://github.com/zephyrproject-rtos/zephyr/pull/76330 should be cherry-picked as fromtree ones
- commit "[nrf noup] drivers: entropy: Switch entropy driver in nRF54L20" should have the following line as the first one in its message body:
`nrf-squash! 
[nrf noup] entropy: Add fake entropy nRF PRNG driver`

2024-09-09 11:05 UTC, kl-cruz commented
Closing as https://github.com/nrfconnect/sdk-zephyr/pull/2000 includes newer changes

2024-09-09 11:05 UTC, closed without merging