[nrf noup] bluetooth: conn: Fix allow for extra ref check in send_buf
nrfconnect/sdk-zephyr pull request #1944
Opened 2024-08-06 13:30 UTC by MarekPieta

With the current implementation, the callback is not passed as an argument to send_buf function call for fragments apart from the last one. Change improves check to prevent spurious assertion failures.

Jira: NCSDK-28624

2024-08-06 14:19 UTC, zycz approved these changes

2024-08-06 15:46 UTC, jori-nordic requested changes
Writing "to prevent spurious assertion failures" right above the assert in question looks like are "fixing the test" instead of fixing the root cause. 

Since this is a `noup`, I suggest removing the assert altogether and having this sentence in the commit message
 
> `send_buf()` can be called multiple times, if `buf` has to be fragmented over HCI. `buf` will have an additional reference taken. We cannot know if the application has provided a callback until the very last fragment. That means we can't assert on the amount of references for fragments here.

2024-08-07 05:27 UTC, MarekPieta commented
> Writing "to prevent spurious assertion failures" right above the assert in question looks like are "fixing the test" instead of fixing the root cause.
> 
> Since this is a `noup`, I suggest removing the assert altogether and having this sentence in the commit message
> 
> > `send_buf()` can be called multiple times, if `buf` has to be fragmented over HCI. `buf` will have an additional reference taken. We cannot know if the application has provided a callback until the very last fragment. That means we can't assert on the amount of references for fragments here.

Actually the commit aligns the assertion to updated implementation (fixing test condition in the assertion). If you insist, I will remove the assertion, but I would suggest to keep it (it validates ref counter properly for the last fragment). I rephrased my comments taking into account your suggestions.

2024-08-07 07:36 UTC, jori-nordic commented
> it validates ref counter properly for the last fragment

yes but the assert was supposed to validate it for every frag. It is weakened enough that we should just remove it altogether.

2024-08-07 08:51 UTC, jori-nordic approved these changes
🚀

2024-08-07 09:18 UTC, zycz approved these changes

2024-08-08 12:11 UTC, alwa-nordic approved these changes

2024-08-09 07:11 UTC, merged