[nrf noup] soc: nordic: add delay after wake up
nrfconnect/sdk-zephyr pull request #1995
Opened 2024-09-03 16:12 UTC by adamkondraciuk

An additional delay after wake-up is needed.

2024-09-04 06:25 UTC, nordic-piks approved these changes

2024-09-04 07:52 UTC, masz-nordic commented
Can you add a comment with why this is needed?

2024-09-05 09:45 UTC, anangl requested changes
It should be justified why this delay is needed and why it is not applied upstream.

2024-09-06 05:56 UTC, karstenkoenig commented on soc/nordic/nrf54h/power.c
> -	nrf_lrcconf_poweron_force_set(NRF_LRCCONF010, NRF_LRCCONF_POWER_DOMAIN_0, false);
This change looks unrelated, and neither change has a comment that marks it as workaround or temporary when a better solution is in place

2024-09-06 11:25 UTC, karstenkoenig commented
To my understanding we shouldn't do the delay method but just wait for a proper fix in sysctrl that doesn't turn on closed loop for fll16m. or is this supposed to fix something else?

2024-09-06 12:35 UTC, closed without merging