[nrf noup] dts: Select SoftDevice Controller DTS binding as default (2)
nrfconnect/sdk-zephyr pull request #2006
Opened 2024-09-05 06:19 UTC by rugeGerritsen

The SoftDevice Controller is a different controller than the open source link layer with a different set of quirks. It should therefore have its own device tree binding.

This commit converts the SoftDevice Controller driver to use this new DTS binding instead of reusing the existing one.

This commit updates or adds additional overlays for existing samples, applications and tests that were using the open source link layer.

This is second attempt after https://github.com/nrfconnect/sdk-zephyr/pull/1940 was reverted in https://github.com/nrfconnect/sdk-zephyr/pull/2004

manifest-pr-skip

2024-09-06 07:11 UTC, nordicjm approved these changes
Would recommend moving this into 2 commits, the dtsi update is likely ok but the samples/tests one is likely to be a merge heck in future upmerges

2024-09-06 07:43 UTC, cvinayak requested changes
ok.... general nit-pick, could you fix all added lines to ensure newline is used for `extra_args`  and line to those multiple parameters are appended.

2024-09-06 07:43 UTC, cvinayak commented on samples/bluetooth/central_iso/sample.yaml
> +    extra_args: OVERLAY_CONFIG=overlay-bt_ll_sw_split.conf SNIPPET="bt-ll-sw-split"
```suggestion
    extra_args:
      - OVERLAY_CONFIG=overlay-bt_ll_sw_split.conf
      - SNIPPET="bt-ll-sw-split"
```

2024-09-06 07:43 UTC, cvinayak commented on samples/bluetooth/direction_finding_connectionless_tx/sample.yaml
> +    extra_args: OVERLAY_CONFIG="overlay-aoa.conf" SNIPPET="bt-ll-sw-split"
```suggestion
    extra_args:
      - OVERLAY_CONFIG="overlay-aoa.conf"
      - SNIPPET="bt-ll-sw-split"
```

2024-09-06 07:43 UTC, cvinayak commented on samples/bluetooth/direction_finding_connectionless_tx/sample.yaml
> +    extra_args: OVERLAY_CONFIG="overlay-aoa.conf"
```suggestion
    extra_args:
      - OVERLAY_CONFIG="overlay-aoa.conf"
```

2024-09-06 07:43 UTC, cvinayak commented on samples/bluetooth/direction_finding_connectionless_rx/sample.yaml
> +    extra_args: OVERLAY_CONFIG="overlay-aod.conf"
```suggestion
    extra_args:
      - OVERLAY_CONFIG="overlay-aod.conf"
```

2024-09-06 07:43 UTC, cvinayak commented on samples/bluetooth/direction_finding_central/sample.yaml
> +    extra_args: OVERLAY_CONFIG="overlay-aod.conf"
```suggestion
    extra_args:
      - OVERLAY_CONFIG="overlay-aod.conf"
```

2024-09-06 07:43 UTC, cvinayak commented on samples/bluetooth/hci_vs_scan_req/sample.yaml
> +    extra_args: SNIPPET="bt-ll-sw-split"
```suggestion
    extra_args:
      - SNIPPET="bt-ll-sw-split"
```

2024-09-06 07:43 UTC, cvinayak commented on tests/bluetooth/controller/ctrl_api/testcase.yaml
> +    extra_args: SNIPPET="bt-ll-sw-split"
```suggestion
    extra_args:
      - SNIPPET="bt-ll-sw-split"
```

2024-09-06 07:43 UTC, cvinayak commented on tests/bluetooth/controller/ctrl_chmu/testcase.yaml
> +    extra_args: SNIPPET="bt-ll-sw-split"
```suggestion
    extra_args:
      - SNIPPET="bt-ll-sw-split"
```

2024-09-06 07:43 UTC, cvinayak commented on tests/bluetooth/controller/ctrl_cis_create/testcase.yaml
> +    extra_args: SNIPPET="bt-ll-sw-split"
```suggestion
    extra_args:
      - SNIPPET="bt-ll-sw-split"
```

2024-09-06 07:43 UTC, cvinayak commented on tests/bluetooth/controller/ctrl_cis_terminate/testcase.yaml
> +    extra_args: SNIPPET="bt-ll-sw-split"
```suggestion
    extra_args:
      - SNIPPET="bt-ll-sw-split"
```

2024-09-06 07:43 UTC, cvinayak commented on tests/bluetooth/controller/ctrl_collision/testcase.yaml
> +    extra_args: SNIPPET="bt-ll-sw-split"
```suggestion
    extra_args:
      - SNIPPET="bt-ll-sw-split"
```

2024-09-06 07:43 UTC, cvinayak commented on tests/bluetooth/controller/ctrl_conn_update/testcase.yaml
> +    extra_args: SNIPPET="bt-ll-sw-split"
```suggestion
    extra_args:
      - SNIPPET="bt-ll-sw-split"
```

2024-09-06 07:43 UTC, cvinayak commented on tests/bluetooth/controller/ctrl_cte_req/testcase.yaml
> +    extra_args: SNIPPET="bt-ll-sw-split"
```suggestion
    extra_args:
      - SNIPPET="bt-ll-sw-split"
```

2024-09-06 07:43 UTC, cvinayak commented on tests/bluetooth/controller/ctrl_data_length_update/testcase.yaml
> +    extra_args: SNIPPET="bt-ll-sw-split"
```suggestion
    extra_args:
      - SNIPPET="bt-ll-sw-split"
```

2024-09-06 07:43 UTC, cvinayak commented on tests/bluetooth/controller/ctrl_encrypt/testcase.yaml
> +    extra_args: SNIPPET="bt-ll-sw-split"
```suggestion
    extra_args:
      - SNIPPET="bt-ll-sw-split"
```

2024-09-06 07:43 UTC, cvinayak commented on tests/bluetooth/controller/ctrl_feature_exchange/testcase.yaml
> +    extra_args: SNIPPET="bt-ll-sw-split"
```suggestion
    extra_args:
      - SNIPPET="bt-ll-sw-split"
```

2024-09-06 07:43 UTC, cvinayak commented on tests/bluetooth/controller/ctrl_invalid/testcase.yaml
> +    extra_args: SNIPPET="bt-ll-sw-split"
```suggestion
    extra_args:
      - SNIPPET="bt-ll-sw-split"
```

2024-09-06 07:43 UTC, cvinayak commented on tests/bluetooth/controller/ctrl_le_ping/testcase.yaml
> +    extra_args: SNIPPET="bt-ll-sw-split"
```suggestion
    extra_args:
      - SNIPPET="bt-ll-sw-split"
```

2024-09-06 07:43 UTC, cvinayak commented on tests/bluetooth/controller/ctrl_min_used_chans/testcase.yaml
> +    extra_args: SNIPPET="bt-ll-sw-split"
```suggestion
    extra_args:
      - SNIPPET="bt-ll-sw-split"
```

2024-09-06 07:43 UTC, cvinayak commented on tests/bluetooth/controller/ctrl_phy_update/testcase.yaml
> +    extra_args: SNIPPET="bt-ll-sw-split"
```suggestion
    extra_args:
      - SNIPPET="bt-ll-sw-split"
```

2024-09-06 07:43 UTC, cvinayak commented on tests/bluetooth/controller/ctrl_sca_update/testcase.yaml
> +    extra_args: SNIPPET="bt-ll-sw-split"
```suggestion
    extra_args:
      - SNIPPET="bt-ll-sw-split"
```

2024-09-06 07:43 UTC, cvinayak commented on tests/bluetooth/controller/ctrl_terminate/testcase.yaml
> +    extra_args: SNIPPET="bt-ll-sw-split"
```suggestion
    extra_args:
      - SNIPPET="bt-ll-sw-split"
```

2024-09-06 07:43 UTC, cvinayak commented on tests/bluetooth/controller/ctrl_tx_buffer_alloc/testcase.yaml
> +    extra_args: SNIPPET="bt-ll-sw-split"
```suggestion
    extra_args:
      - SNIPPET="bt-ll-sw-split"
```

2024-09-10 13:28 UTC, jori-nordic approved these changes

2024-09-11 07:08 UTC, merged