[nrf noup] modules: mbedtls: Add Nordic only PSA wants
nrfconnect/sdk-zephyr pull request #2077
Opened 2024-10-08 08:48 UTC by Vge0rge

Add some Nordic only PSA want Kconfig options which were missplaced in nrf_security during the upmerge.

2024-10-08 11:44 UTC, tomi-font approved these changes

2024-10-08 11:47 UTC, tejlmand requested changes
we should not be creating `noup` patches for things that can line in downstream repos.

Why is this being moved to a noup patch ?
it will just make future upmerges harder to handle of this principle spreads.

This is why we try to make Zephyr modular so downstream stuff can stay in the downstream repos.

2024-10-15 11:56 UTC, Vge0rge commented
> we should not be creating `noup` patches for things that can line in downstream repos.
> 
> Why is this being moved to a noup patch ? it will just make future upmerges harder to handle of this principle spreads.
> 
> This is why we try to make Zephyr modular so downstream stuff can stay in the downstream repos.

What you say make sense to me @tejlmand , so I just reverted the noup here and I moved the file in nrf_security.

2024-10-15 12:17 UTC, frkv approved these changes
Good improvement that I didn't dare to do in the upmerge

LGTM and hoping we don't have any dependency for the nordic-only configurations

Fingers crossed for clean CI!

2024-10-23 11:17 UTC, merged