Pull in PRF-256 Implementation from upstream Hostap
nrfconnect/sdk-zephyr pull request #2085
Opened 2024-10-09 02:36 UTC by VivekUppunda

This Pulls in PRF-256 code from upstream hostap. Picking a SHA commit which is 1 level above my commit SHA for upstream as there is a CI build fix in this SHA for my commit.

2024-10-09 02:37 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| hostap | https://github.com/zephyrproject-rtos/hostap/commit/cbae0170437dbe196d436b2b53d7aefb97044b0c | https://github.com/zephyrproject-rtos/hostap/commit/9896a2ea803ec62e0998c0e569f12af88537d647 | [zephyrproject-rtos/hostap@cbae0170..9896a2ea](https://github.com/zephyrproject-rtos/hostap/compare/cbae0170437dbe196d436b2b53d7aefb97044b0c..9896a2ea803ec62e0998c0e569f12af88537d647) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2024-10-09 06:52 UTC, sachinthegreen approved these changes

2024-10-14 06:52 UTC, nordicjm requested changes
how can this be a fromtree when this replaces `cbae0170437dbe196d436b2b53d7aefb97044b0c` and the upstream replaces `291e1cd0dfad83ec02826adf48dd6db69c3471ca`

2024-10-14 08:16 UTC, VivekUppunda commented
> how can this be a fromtree when this replaces `cbae0170437dbe196d436b2b53d7aefb97044b0c` and the upstream replaces `291e1cd0dfad83ec02826adf48dd6db69c3471ca`

Kindly check - updated the commits.

2024-10-16 13:39 UTC, merged