[nrf fromtree] samples: Align tests yaml and overlays to nrf54l15dk
nrfconnect/sdk-zephyr pull request #2099
Opened 2024-10-11 13:50 UTC by jaz1-nordic

Align mbox sample.yaml and icmsg flpr overlays to nrf54l15dk.

Signed-off-by: Jakub Zymelka <jakub.zymelka@nordicsemi.no>
(cherry picked from commit 3904c3b2fe0ceb84cdacb2ae28fe949f326d0442)

2024-10-11 14:17 UTC, masz-nordic approved these changes

2024-10-11 14:20 UTC, magp-nordic approved these changes

2024-10-14 07:24 UTC, nordicjm requested changes
You have changed the commit because `3904c3b2fe0ceb84cdacb2ae28fe949f326d0442` does not apply cleanly

2024-10-16 10:26 UTC, jaz1-nordic commented
Duplicated. Previous PR here: https://github.com/nrfconnect/sdk-zephyr/pull/2069

2024-10-16 10:26 UTC, closed without merging