[nrf fromlist] nRF54H20 EngB fixes
nrfconnect/sdk-zephyr pull request #2147
Opened 2024-10-22 12:24 UTC by 57300

2024-10-23 09:55 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| hal_nxp | https://github.com/zephyrproject-rtos/hal_nxp/commit/77815705c465627b8436cbac51f0bf0594bbeba2 | https://github.com/zephyrproject-rtos/hal_nxp/commit/f4e26fad2cfd8b8e8988e835a28667573ed072cf | [zephyrproject-rtos/hal_nxp@77815705..f4e26fad](https://github.com/zephyrproject-rtos/hal_nxp/compare/77815705c465627b8436cbac51f0bf0594bbeba2..f4e26fad2cfd8b8e8988e835a28667573ed072cf) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2024-11-19 14:03 UTC, miha-nordic approved these changes

2024-11-20 07:16 UTC, nika-nordic approved these changes

2024-11-21 14:57 UTC, nordic-segl commented on tests/drivers/uart/uart_async_api/boards/nrf54l15pdk_nrf54l15_cpuflpr.overlay
I see there is no overlay for nrf54l15dk_nrf54l15_cpuflpr. Should this file be deleted or renamed?

2024-11-21 14:59 UTC, nordic-segl commented on tests/drivers/pwm/pwm_api/boards/nrf54l15pdk_nrf54l15_cpuapp.overlay
I see there is no overlay for nrf54l15dk_nrf54l15_cpuflpr. Should this file be deleted or renamed?

2024-11-21 15:02 UTC, nordic-segl commented on tests/drivers/gpio/gpio_basic_api/boards/nrf54l15pdk_nrf54l15_cpuflpr.overlay
Rename to dk instead of deleting?

2024-11-21 15:02 UTC, nordic-segl commented on tests/drivers/gpio/gpio_basic_api/boards/nrf54l15pdk_nrf54l15_cpuflpr_xip.overlay
Rename to dk instead of deleting?

2024-11-21 16:24 UTC, nordic-segl approved these changes

2024-11-25 07:08 UTC, nordic-segl requested changes
You are removing
[tests/drivers/gpio/gpio_basic_api/boards/nrf54l15pdk_nrf54l15_cpuflpr.overlay](https://github.com/nrfconnect/sdk-zephyr/pull/2147/files#diff-572b14dbd65809f47b404ef858189413610f9339bb480958759f26eb49192f4d)
However, there is no overlay for DK. Same for ...cpuflpr_xip.overlay
Shall this file be renamed instead of deleted?

2024-11-25 17:42 UTC, carlescufi commented
> You are removing [tests/drivers/gpio/gpio_basic_api/boards/nrf54l15pdk_nrf54l15_cpuflpr.overlay](https://github.com/nrfconnect/sdk-zephyr/pull/2147/files#diff-572b14dbd65809f47b404ef858189413610f9339bb480958759f26eb49192f4d) However, there is no overlay for DK. Same for ...cpuflpr_xip.overlay Shall this file be renamed instead of deleted?

Let me solve the build issues first and then I can address this in a follow-up PR please @nordic-segl. This "mini upmerge" is complicated enough as it is and it requires a follow-up of overlays anyway that I have here:
https://github.com/zephyrproject-rtos/zephyr/pull/81711

2024-11-26 07:09 UTC, nordic-segl approved these changes

2024-11-27 11:21 UTC, merged

2024-11-28 06:10 UTC, nordic-piks commented
> You are removing [tests/drivers/gpio/gpio_basic_api/boards/nrf54l15pdk_nrf54l15_cpuflpr.overlay](https://github.com/nrfconnect/sdk-zephyr/pull/2147/files#diff-572b14dbd65809f47b404ef858189413610f9339bb480958759f26eb49192f4d) However, there is no overlay for DK. Same for ...cpuflpr_xip.overlay Shall this file be renamed instead of deleted?

Fixed here; #82200