[nrf noup] sample/smp_svr: nrf54l15dk test cases
nrfconnect/sdk-zephyr pull request #2167
Opened 2024-10-25 12:25 UTC by nvlsianpu

Added nrf54l15dk testcases as copies of nrf54l15pdk.

2024-10-28 08:44 UTC, nordicjm requested changes
Should be a fixup and replace the pdk entries

2024-11-06 13:03 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| hal_nordic | https://github.com/zephyrproject-rtos/hal_nordic/commit/bc25c094a8cf3064f4f9c1e8060b46e1989edf95 | https://github.com/zephyrproject-rtos/hal_nordic/commit/2d78179cc4f0601a891553132b13184fa51b6ef9 (master) | [zephyrproject-rtos/hal_nordic@bc25c094..2d78179c](https://github.com/zephyrproject-rtos/hal_nordic/compare/bc25c094a8cf3064f4f9c1e8060b46e1989edf95..2d78179cc4f0601a891553132b13184fa51b6ef9) |
| hostap | https://github.com/zephyrproject-rtos/hostap/commit/9896a2ea803ec62e0998c0e569f12af88537d647 | https://github.com/zephyrproject-rtos/hostap/commit/44285310338f423021cc7df2c1056256882a00cc | [zephyrproject-rtos/hostap@9896a2ea..44285310](https://github.com/zephyrproject-rtos/hostap/compare/9896a2ea803ec62e0998c0e569f12af88537d647..44285310338f423021cc7df2c1056256882a00cc) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2024-11-06 15:28 UTC, de-nordic approved these changes

2024-11-06 17:44 UTC, michalek-no commented
rebase

2024-11-07 07:31 UTC, nordicjm approved these changes

2024-11-07 10:06 UTC, gchwier approved these changes

2024-11-07 10:51 UTC, merged