[nrf fromlist] modules: hal_nordic: NRFS support for P11 power switch.
nrfconnect/sdk-zephyr pull request #2208
Opened 2024-10-31 09:44 UTC by JuhaKortesalmi

Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/80657

2024-10-31 09:45 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| hal_nordic | https://github.com/zephyrproject-rtos/hal_nordic/commit/c1c448df1b751c1c03229a447a2216f29e6aaf99 | https://github.com/zephyrproject-rtos/hal_nordic/pull/239 | [zephyrproject-rtos/hal_nordic#239/files](https://github.com/zephyrproject-rtos/hal_nordic/pull/239/files) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2024-11-08 10:16 UTC, carlescufi requested changes
We cannot pull a change that points to a PR

2024-11-08 13:06 UTC, carlescufi approved these changes

2024-11-13 10:24 UTC, JuhaKortesalmi commented
> > We cannot pull a change that points to a PR
> 
> We also cannot point to an unmerged SHA. PR [zephyrproject-rtos/hal_nordic#239](https://github.com/zephyrproject-rtos/hal_nordic/pull/239) needs to be merged first.

So there is conflict between comments, which one I choose, full SHA or "pull/PR/head"?

2024-11-13 10:37 UTC, 57300 commented
> > > We cannot pull a change that points to a PR
> > 
> > 
> > We also cannot point to an unmerged SHA. PR [zephyrproject-rtos/hal_nordic#239](https://github.com/zephyrproject-rtos/hal_nordic/pull/239) needs to be merged first.
> 
> So there is conflict between comments, which one I choose, full SHA or "pull/PR/head"?

You should use pull/#/head while the hal_nordic PR is still open. Only update to SHA after it's merged.
Right now you're using an "impostor" SHA from your own fork.

What @carlescufi meant is that we cannot merge this sdk-zephyr PR until the hal_nordic PR is merged.

2024-12-30 04:41 UTC, closed without merging