[nrf noup] samples: mgmt: mcumgr: smp_svr: Add nrf5340dk-optimised sample
nrfconnect/sdk-zephyr pull request #2269
Opened 2024-11-13 14:30 UTC by nordicjm

Adds a configuration to this sample that is optimised for testing/usage with the nRF5340 which enables the Bluetooth transport, enables most management groups, has a static partition manager file with secondary partitions on QSPI flash, configures MCUboot in overwrite only mode with network core update support

2024-11-19 19:05 UTC, nvlsianpu requested changes
Multiple board configuration/overlay files was added in the sample's sysbuild/mcuboot/boards directory as well (not only nRF540dk).
I see that many of the can be involved into the build configuration as I'm recognizing them as their copies from MCUBoot's repository.

1. What intention behind that?
2. Why 3-rd party board files are added?
3. Should we remove original files from MCUboot's repository?

2024-11-20 06:43 UTC, nordicjm commented
>     1. What intention behind that?

So that this sample can be used with any (nordic-based) board still, as the files in MCUboot will not be used

>     2. Why 3-rd party board files are added?

As above, only nordic-based boards are added

>     3. Should we remove original files from MCUboot's repository?

No

2024-11-20 06:44 UTC, nordicjm commented
Would add that this is only need due to, yet again, partition manager

2024-11-22 16:51 UTC, nvlsianpu approved these changes

2024-11-29 08:53 UTC, gchwier approved these changes
nit: nrf54l15PDK can be removed, only DK is now supported
nit2: do we need pm_static files? Partition Manager should generate pm_static

and it is not fine that we need to copy all those configs from MCUboot repo when using sysbuild. As I remember, for child images those configs were taken as a default parameters, and overwritten by sample configs, now if we have any file/folder in sysbuild dir we must copy defaults to the project dir :(

2024-12-02 16:31 UTC, nvlsianpu commented on samples/subsys/mgmt/mcumgr/smp_svr/sysbuild/mcuboot/app.overlay
Will we can avoid many of *.conf files copies If this file will be removed?

2024-12-03 11:08 UTC, nordicjm commented on samples/subsys/mgmt/mcumgr/smp_svr/sysbuild/mcuboot/app.overlay
Have reworked PR, all these files are now gone

2024-12-16 14:42 UTC, nvlsianpu commented
@nordicjm Can you rebase this?

2025-01-16 14:54 UTC, nvlsianpu commented
@nordicjm Can be merged.

2025-01-16 15:00 UTC, de-nordic approved these changes

2025-01-28 16:43 UTC, nvlsianpu commented
@nrfconnect/ncs-test-leads Please give tick.

2025-01-29 07:44 UTC, miha-nordic commented
> @nrfconnect/ncs-test-leads Please give tick.

CI is red. Please take a look on DFU tests.

2025-02-17 14:00 UTC, merged