Oct 3214 cherry pick required pts fixes from upstream
nrfconnect/sdk-zephyr pull request #2294
Opened 2024-11-22 13:44 UTC by koffes

2024-11-22 13:45 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| nrf_hw_models | https://github.com/zephyrproject-rtos/nrf_hw_models/commit/eeed2591d38e5e9bf89658df67555f2777249fc0 | https://github.com/zephyrproject-rtos/nrf_hw_models/commit/aca798cf7cf0c5dc1fd89c66cf62670051feb8d0 | [zephyrproject-rtos/nrf_hw_models@eeed2591..aca798cf](https://github.com/zephyrproject-rtos/nrf_hw_models/compare/eeed2591d38e5e9bf89658df67555f2777249fc0..aca798cf7cf0c5dc1fd89c66cf62670051feb8d0) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2024-11-25 12:52 UTC, alexsven approved these changes

2024-11-25 13:39 UTC, Frodevan requested changes
Consistently fails downstream testing for test-sdk-audio.

2024-11-25 15:46 UTC, Frodevan approved these changes
Passes with proposed changes to NCS

2024-11-26 12:25 UTC, merged