[nrf noup] drivers: flash: Allow reading secure mem by nrf_rram.
nrfconnect/sdk-zephyr pull request #2352
Opened 2024-12-10 08:30 UTC by ArekBalysNordic

To read the secure memory we need to use soc_secure_mem_read function instead of memcpy.

This commit allows to use the soc_secure_mem_read function if the CONFIG_TRUSTED_EXECUTION_NONSECURE and PARTITION_MANAGER is enabled.

2024-12-10 10:58 UTC, nordicjm requested changes

2024-12-10 11:42 UTC, ArekBalysNordic commented on drivers/flash/soc_flash_nrf_rram.c
Done.

2024-12-11 09:27 UTC, de-nordic approved these changes

2024-12-11 10:09 UTC, ArekBalysNordic commented
There was an issue with Radio Driver, rebasing.

2024-12-11 10:45 UTC, nordicjm approved these changes

2024-12-11 12:08 UTC, LuDuda approved these changes

2024-12-11 13:11 UTC, nvlsianpu approved these changes

2024-12-11 13:31 UTC, ArekBalysNordic commented
rebased.

2024-12-12 08:44 UTC, merged