openthread: logging: Fix platform log linking in NCP
nrfconnect/sdk-zephyr pull request #372
Opened 2020-10-14 11:18 UTC by pszkotak

This PR ensures that `otPlatLog` is compiled in always when `CONFIG_OPENTHREAD_DEBUG` is set.
It fixes the NCP sample linking.

Signed-off-by: Piotr Szkotak <piotr.szkotak@nordicsemi.no>

2020-10-14 11:22 UTC, rlubos requested changes
Please add `[nrf toup]` prefix to the commit title. Or even better, open an upstream PR and add the `[nrf fromlist]` prefix.
And please open a manifest update in the `sdk-nrf` repo.

2020-10-14 12:37 UTC, rlubos approved these changes
tHANKS

2020-10-15 07:41 UTC, edmont approved these changes

2020-10-15 09:35 UTC, MarekPorwisz approved these changes

2020-10-16 07:40 UTC, shantha-14 approved these changes

2020-10-16 09:41 UTC, carlescufi commented
I'd much rather see a `[nrf fromlist]` here. Are you going to post a PR to upstream zephyr?

2020-10-16 11:52 UTC, pszkotak commented
> I'd much rather see a `[nrf fromlist]` here. Are you going to post a PR to upstream zephyr?

Done.
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/29266

2020-10-16 15:26 UTC, pszkotak commented
Closing this one, different solution has been chosen.

2020-10-16 15:26 UTC, closed without merging