Rebase history
nrfconnect/sdk-zephyr pull request #381
Opened 2020-10-21 03:20 UTC by mbolivar-nordic

Empty diff from manifest-rev at time of writing, which is 45f2d5cf8ea437b9189255691980a4dc140b7a2b.

I didn't do any cleanup besides rebasing our OOT patches on top of upstream history in the same order `west ncs-loot` prints them.

Opening a PR just for review purposes; this of course needs to be pushed by hand.

2020-10-21 03:38 UTC, NordicBuilder commented
**Some checks failed. Please fix and resubmit.**

## checkpatch (informational only, not a failure)

```
-:447: WARNING:LONG_LINE_STRING: line length of 84 exceeds 80 columns
#447: FILE: drivers/ieee802154/ieee802154_nrf5.c:413:
+			LOG_WRN(&quot;TX_STARTED event will be triggered without delay&quot;);

-:853: WARNING:LEADING_SPACE: please, no spaces at the start of a line
#853: FILE: include/net/socket.h:839:
+    char ifr_name[IFNAMSIZ]; /* Interface name */$

-:1503: WARNING:BLOCK_COMMENT_STYLE: Block comments should align the * on each line
#1503: FILE: subsys/net/lib/lwm2m/lwm2m_engine.c:2254:
+		/* Restore the opaque context from the block context, if used.
+		*/

- total: 0 errors, 3 warnings, 1755 lines checked

NOTE: For some of the reported defects, checkpatch may be able to
      mechanically convert to the typical style using --fix or --fix-inplace.

Your patch has style problems, please review.

NOTE: Ignored message types: AVOID_EXTERNS BRACES C99_COMMENT_TOLERANCE CONFIG_EXPERIMENTAL CONST_STRUCT DATE_TIME FILE_PATH_CHANGES MINMAX NETWORKING_BLOCK_COMMENT_STYLE PREFER_KERNEL_TYPES PRINTK_WITHOUT_KERN_LEVEL REPEATED_WORD SPDX_LICENSE_TAG SPLIT_STRING VOLATILE

NOTE: If any of the errors are false positives, please report
      them to the maintainers.

```

## Gitlint issues

Commit ebda60d875:
1: UC5 Title exceeds max length (80>75): "[nrf fromtree] net: lwm2m: Report boostrap complete after final response is sent"

Commit ee286f52c3:
1: UC5 Title exceeds max length (76>75): "[nrf fromtree] net: lwm2m: Use the actual data size when provisioning PSK ID"

Commit c5afa3d650:
1: UC5 Title exceeds max length (82>75): "[nrf fromtree] net: lwm2m: Store the actual resource size in the resource instance"

Commit 5e02ab2166:
1: UC5 Title exceeds max length (77>75): "[nrf fromtree] net: lwm2m: Fix FOTA block transfer with opaque content-format"

## pylint issues

```
************* Module kconfigfunctions
scripts/kconfig/kconfigfunctions.py:444:12: W0109: Duplicate key 'dt_alias_enabled' in dictionary (duplicate-key)
```



*Tip: The bot edits this comment instead of posting a new one, so you can check the comment's history to see earlier messages.*

2020-10-21 03:43 UTC, mbolivar-nordic commented
> **Some checks failed. Please fix and resubmit.**

I'm going to ignore these. I can't make any changes that would alter source code, and I think gitlint ought to be ignored so `west ncs-compare` can still track these fromtree patches accurately by shortlog. Maybe there's some way to reconfigure it so it strips sauce tags before checking line length?

2020-10-21 05:43 UTC, joerchan approved these changes

2020-10-21 07:28 UTC, rlubos requested changes
> Empty diff from manifest-rev at time of writing, which is [45f2d5c](https://github.com/nrfconnect/sdk-zephyr/commit/45f2d5cf8ea437b9189255691980a4dc140b7a2b).

`sdk-zephyr` master is one commit ahead, the manifest update in `sdk-nrf` hasn't been merged yet:
https://github.com/zephyrproject-rtos/openthread/commit/f9fbfad0119d7b0d473eaac50c2f0a0a483c2823

2020-10-21 09:01 UTC, thst-nordic commented
I started the CI and have skipped the compliance stage.

2020-10-21 13:21 UTC, thst-nordic commented
you can ignore the failing statuses from (build 1.)

2020-10-21 14:30 UTC, mbolivar-nordic commented
> `sdk-zephyr` master is one commit ahead, the manifest update in `sdk-nrf` hasn't been merged yet:
> [zephyrproject-rtos/openthread@f9fbfad](https://github.com/zephyrproject-rtos/openthread/commit/f9fbfad0119d7b0d473eaac50c2f0a0a483c2823)

@rlubos I don't follow; `$ git diff 45f2d5cf8ea437b9189255691980a4dc140b7a2b ncs-v1.4.0-rebase` prints nothing.

2020-10-21 14:32 UTC, mbolivar-nordic commented
Ah, I see, someone else merged into sdk-zephyr.

2020-10-21 14:43 UTC, rlubos approved these changes

2020-10-21 14:52 UTC, NordicBuilder commented
**Some checks failed. Please fix and resubmit.**

## checkpatch (informational only, not a failure)

```
-:447: WARNING:LONG_LINE_STRING: line length of 84 exceeds 80 columns
#447: FILE: drivers/ieee802154/ieee802154_nrf5.c:413:
+			LOG_WRN(&quot;TX_STARTED event will be triggered without delay&quot;);

-:853: WARNING:LEADING_SPACE: please, no spaces at the start of a line
#853: FILE: include/net/socket.h:839:
+    char ifr_name[IFNAMSIZ]; /* Interface name */$

-:1521: WARNING:BLOCK_COMMENT_STYLE: Block comments should align the * on each line
#1521: FILE: subsys/net/lib/lwm2m/lwm2m_engine.c:2254:
+		/* Restore the opaque context from the block context, if used.
+		*/

- total: 0 errors, 3 warnings, 1795 lines checked

NOTE: For some of the reported defects, checkpatch may be able to
      mechanically convert to the typical style using --fix or --fix-inplace.

Your patch has style problems, please review.

NOTE: Ignored message types: AVOID_EXTERNS BRACES C99_COMMENT_TOLERANCE CONFIG_EXPERIMENTAL CONST_STRUCT DATE_TIME FILE_PATH_CHANGES MINMAX NETWORKING_BLOCK_COMMENT_STYLE PREFER_KERNEL_TYPES PRINTK_WITHOUT_KERN_LEVEL REPEATED_WORD SPDX_LICENSE_TAG SPLIT_STRING VOLATILE

NOTE: If any of the errors are false positives, please report
      them to the maintainers.

```

## Gitlint issues

Commit ebda60d875:
1: UC5 Title exceeds max length (80>75): "[nrf fromtree] net: lwm2m: Report boostrap complete after final response is sent"

Commit ee286f52c3:
1: UC5 Title exceeds max length (76>75): "[nrf fromtree] net: lwm2m: Use the actual data size when provisioning PSK ID"

Commit c5afa3d650:
1: UC5 Title exceeds max length (82>75): "[nrf fromtree] net: lwm2m: Store the actual resource size in the resource instance"

Commit 5e02ab2166:
1: UC5 Title exceeds max length (77>75): "[nrf fromtree] net: lwm2m: Fix FOTA block transfer with opaque content-format"

## pylint issues

```
************* Module kconfigfunctions
scripts/kconfig/kconfigfunctions.py:444:12: W0109: Duplicate key 'dt_alias_enabled' in dictionary (duplicate-key)
```



*Tip: The bot edits this comment instead of posting a new one, so you can check the comment's history to see earlier messages.*

2020-10-22 12:00 UTC, nvlsianpu approved these changes

2020-10-22 19:18 UTC, thst-nordic approved these changes

2020-10-24 06:45 UTC, joerchan commented
@mbolivar-nordic This one will have to be handled:
https://github.com/nrfconnect/sdk-zephyr/pull/382

2020-10-24 08:36 UTC, mbolivar-nordic commented
@joerchan

Sure, I'll cherry pick any patches that make it into the current master into the rebase branch on Sunday.

2020-10-26 00:01 UTC, NordicBuilder commented
**Some checks failed. Please fix and resubmit.**

## checkpatch (informational only, not a failure)

```
-:447: WARNING:LONG_LINE_STRING: line length of 84 exceeds 80 columns
#447: FILE: drivers/ieee802154/ieee802154_nrf5.c:413:
+			LOG_WRN(&quot;TX_STARTED event will be triggered without delay&quot;);

-:853: WARNING:LEADING_SPACE: please, no spaces at the start of a line
#853: FILE: include/net/socket.h:839:
+    char ifr_name[IFNAMSIZ]; /* Interface name */$

-:1543: WARNING:BLOCK_COMMENT_STYLE: Block comments should align the * on each line
#1543: FILE: subsys/net/lib/lwm2m/lwm2m_engine.c:2254:
+		/* Restore the opaque context from the block context, if used.
+		*/

- total: 0 errors, 3 warnings, 1811 lines checked

NOTE: For some of the reported defects, checkpatch may be able to
      mechanically convert to the typical style using --fix or --fix-inplace.

Your patch has style problems, please review.

NOTE: Ignored message types: AVOID_EXTERNS BRACES C99_COMMENT_TOLERANCE CONFIG_EXPERIMENTAL CONST_STRUCT DATE_TIME FILE_PATH_CHANGES MINMAX NETWORKING_BLOCK_COMMENT_STYLE PREFER_KERNEL_TYPES PRINTK_WITHOUT_KERN_LEVEL REPEATED_WORD SPDX_LICENSE_TAG SPLIT_STRING VOLATILE

NOTE: If any of the errors are false positives, please report
      them to the maintainers.

```

## Gitlint issues

Commit ebda60d875:
1: UC5 Title exceeds max length (80>75): "[nrf fromtree] net: lwm2m: Report boostrap complete after final response is sent"

Commit ee286f52c3:
1: UC5 Title exceeds max length (76>75): "[nrf fromtree] net: lwm2m: Use the actual data size when provisioning PSK ID"

Commit c5afa3d650:
1: UC5 Title exceeds max length (82>75): "[nrf fromtree] net: lwm2m: Store the actual resource size in the resource instance"

Commit 5e02ab2166:
1: UC5 Title exceeds max length (77>75): "[nrf fromtree] net: lwm2m: Fix FOTA block transfer with opaque content-format"

## pylint issues

```
************* Module kconfigfunctions
scripts/kconfig/kconfigfunctions.py:444:12: W0109: Duplicate key 'dt_alias_enabled' in dictionary (duplicate-key)
```



*Tip: The bot edits this comment instead of posting a new one, so you can check the comment's history to see earlier messages.*

2020-10-26 18:35 UTC, merged