Tfm modem
nrfconnect/sdk-zephyr pull request #437
Opened 2021-02-01 12:59 UTC by oyvindronningstad

2021-02-02 16:01 UTC, mbolivar-nordic commented
Please rebase this PR if still relevant; master has been rebased.

2021-02-04 07:19 UTC, hakonfam approved these changes

2021-02-04 16:13 UTC, mbolivar-nordic commented
@hakonfam you've still got -1 on https://github.com/nrfconnect/sdk-nrf/pull/3790/files, so I'm assuming you don't want this merged yet.

2021-02-08 10:51 UTC, hakonfam commented
> @hakonfam you've still got -1 on [nrfconnect/sdk-nrf#3790](https://github.com/nrfconnect/sdk-nrf/pull/3790), so I'm assuming you don't want this merged yet.

I guess we should wait with merging until the parent PR is approved at least.

2021-02-09 12:54 UTC, ioannisg approved these changes
Looks fine to me.
@oyvindronningstad can you take a look at the related upstream PRs, where I am sure I have left some comments in the PR reviews? MAybe you can bring some of those here.

2021-02-09 15:03 UTC, tejlmand requested changes
I propose a choice, to make it clear what options the user has, and to make the default follow how Zephyr is configured.

2021-02-10 10:27 UTC, oyvindronningstad commented on modules/Kconfig.tfm
> +	  Choose from Debug, Release, RelWithDebInfo, and MinSizeRel
Done

2021-02-10 11:36 UTC, tejlmand approved these changes
Looks good.
Consider shorten the build type prompt.

2021-02-10 11:36 UTC, tejlmand commented on modules/Kconfig.tfm
> +	prompt "The build type sent to the TFM build system"
Just did a UI try of this:
![image](https://user-images.githubusercontent.com/9802583/107504780-179a7200-6b9c-11eb-8f41-f69e64dd8a01.png)

Maybe shorten this to:
![image](https://user-images.githubusercontent.com/9802583/107504974-53cdd280-6b9c-11eb-8ca6-5035c195b905.png)

```suggestion
	prompt "TFM build type"
```

2021-02-10 19:49 UTC, merged