[nrf toup] boards: Add KConfig option to allow the app core to run at…
nrfconnect/sdk-zephyr pull request #461
Opened 2021-02-11 15:31 UTC by jostn

Add KConfig option to allow the app core to run at 128MHz

Signed-off-by: Johan Stridkvist <johan.stridkvist@nordicsemi.no>

2021-02-22 14:30 UTC, ioannisg commented on boards/arm/nrf5340dk_nrf5340/Kconfig
> +	default n
no need for default n, this is default anways

2021-02-22 14:30 UTC, ioannisg commented on soc/arm/nordic_nrf/nrf53/Kconfig.soc
> +	default n
ditto

2021-02-23 17:54 UTC, carlescufi requested changes
This should be `fromtree` or `fromlist`

2021-06-11 16:02 UTC, mbolivar-nordic commented
Please rebase if still needed downstream, as this is not yet merged upstream

2021-06-23 10:34 UTC, closed without merging