[nrf noup] dts: Adding cryptocell_sw as chosen entropy
nrfconnect/sdk-zephyr pull request #462
Opened 2021-02-15 09:43 UTC by frkv

-Adding cryptocell_sw as a chosen entropy source as the non-secure
 does not have access to a entropy peripheral and need to SPM (and
 later PSA APIs through the same driver
-Not upstream as driver is only downstream

ref: NCSDK-8246

Signed-off-by: Frank Audun Kvamtrø <frank.kvamtro@nordicsemi.no>

2021-02-15 09:46 UTC, frkv commented
Note that we have not changed the name of the file entropy_cc310.c into entropy_cc3xx.c so the statement in the comment is still pointing to entropy_cc310 driver even though  nrF5340 has a Arm CryptoCell CC312 HW peripheral. The file-name change will happen at a later time

2021-02-18 12:21 UTC, ioannisg approved these changes
@frkv this is already supported in the same way for nRF9160 NS, right?

2021-02-18 12:24 UTC, tejlmand approved these changes

2021-02-18 12:56 UTC, anangl approved these changes

2021-02-18 13:31 UTC, anangl requested changes
A binding for "nordic,nrf-cc312-sw" should be also added.

2021-02-18 13:33 UTC, ioannisg commented
> A binding for "nordic,nrf-cc312-sw" should be also added.

Right, i guess the existing one is the 310 :)

2021-02-18 13:41 UTC, anangl commented
> > A binding for "nordic,nrf-cc312-sw" should be also added.
> 
> Right, i guess the existing one is the 310 :)

Yes, either the compatible property in the added node needs to be changed to "nordic,nrf-cc310-sw" or a new binding matching the "nordic,nrf-cc312-sw" string needs to be provided. I'm not sure what was the original intention of handling this.

2021-02-18 14:45 UTC, ioannisg commented
@anangl I added a binding file for the 312 "sw" cryptocell. I thought of taking the second option, as more future-proof, in case the two sw-devices will ever need to support different features.

2021-02-18 14:45 UTC, anangl approved these changes

2021-02-18 16:10 UTC, frkv commented
LGTM. Pending zephyr testing

2021-02-18 20:34 UTC, merged