bluetooth: Bluetooth configuration for RPC
nrfconnect/sdk-zephyr pull request #485
Opened 2021-03-15 10:40 UTC by KAGA164

This changes allow to use Bluetooth over RPC when a full BLE stack
is ran on the other core.

2021-04-28 15:08 UTC, doki-nordic requested changes

2021-04-28 15:08 UTC, doki-nordic commented on subsys/bluetooth/CMakeLists.txt
> -add_subdirectory_ifdef(CONFIG_BT_CONN services)
Why `add_subdirectory_ifdef(CONFIG_BT_CONN services)` was removed?

2021-05-13 12:37 UTC, grochu approved these changes

2021-05-31 13:20 UTC, doki-nordic approved these changes

2021-05-31 14:02 UTC, joerchan approved these changes

2021-05-31 14:36 UTC, trond-snekvik approved these changes

2021-06-10 13:10 UTC, tejlmand approved these changes

2021-06-10 16:19 UTC, merged

2021-06-10 16:20 UTC, tejlmand commented
@KAGA164 and @doki-nordic changed commit title to a `[nrf temphack]` as this should be reworked into a cleaner solution, especially regarding the `if (NOT CONFIG_BT_RPC_CLIENT)` check in CMakeLists.txt.