[nrf fromlist] soc: nrf52805: fix enabled instance 0 check
nrfconnect/sdk-zephyr pull request #505
Opened 2021-04-21 04:54 UTC by mbolivar-nordic

Upstream:
https://github.com/zephyrproject-rtos/zephyr/pull/34433/

UART0, TWI0, and SPI0 have different peripheral IDs (2, 3, and 4
respectively) on this SoC and therefore should not be mutually
exclusive to use.

Signed-off-by: Martí Bolívar <marti.bolivar@nordicsemi.no>

2021-04-21 06:19 UTC, anangl approved these changes

2021-04-22 10:16 UTC, tejlmand approved these changes

2021-05-07 07:28 UTC, ioannisg commented
These can be from-tree, now

2021-05-07 07:29 UTC, ioannisg requested changes
from-tree, otherwise, fine.

2021-05-20 14:53 UTC, mbolivar-nordic commented
brought in by the current upmerge

2021-05-20 14:53 UTC, closed without merging