Bluetooth: Additional NCS 1.6 changes
nrfconnect/sdk-zephyr pull request #544
Opened 2021-06-08 08:57 UTC by trond-snekvik

2021-06-08 09:26 UTC, rugeGerritsen approved these changes
Reviewed non-mesh related changes

2021-06-08 11:36 UTC, ioannisg requested changes
wait for TFM to get merged first

2021-06-09 07:40 UTC, ioannisg approved these changes

2021-06-09 11:34 UTC, trond-snekvik commented
Replaced by #546.

2021-06-09 11:34 UTC, closed without merging