DNM: DNM-FAILURE-LIST.md
nrfconnect/sdk-zephyr pull request #556
Opened 2021-06-15 13:50 UTC by thst-nordic

Signed-off-by: Thomas Stilwell <Thomas.Stilwell@nordicsemi.no>

2021-06-15 14:12 UTC, PerMac commented
If I understood correctly during the release sync up, it seems these errors should be solved by updating hal_nordic in sdk-zephyr and @czeslawmakarski will take care of it.

2021-06-15 14:19 UTC, carlescufi requested changes
blocking for now

2021-06-15 15:06 UTC, PerMac commented
@czeslawmakarski I think it might be cleaner to follow these steps for the required fixes (@carlescufi  @thst-nordic please verify):
- create new PR to sdk-zephyr with a commit updating sdk-zephyr's west.yml. Use a proper souce tag in the commit title (@carles which tag should be used in this case?)
- create a new PR to sdk-nrf, where in its west.yml you point to the PR in sdk-zephyr. This will start the CI tests and allow to see if the problem is fixed. E.g. like this: https://github.com/nrfconnect/sdk-nrf/pull/4820
- If the CI passes we will merge sdk-zephyr PR, change the PR in the sdk-nrf to change manifest to use SHA instead of PRs head and merge that one as well.

2021-06-15 15:08 UTC, thst-nordic commented
hal_nordic fixed all the errors except for entropy testcase. 
![image](https://user-images.githubusercontent.com/14976801/122077738-4780ad00-cdfc-11eb-9c68-194ae36e2140.png)
![image](https://user-images.githubusercontent.com/14976801/122077768-4ea7bb00-cdfc-11eb-803d-cf6dcd3bfbb8.png)

2021-06-15 15:16 UTC, czeslawmakarski commented
@PerMac While I do agree with you on a general basis, this time @thst-nordic explicitly asked me to push a fix to this branch.

2021-06-16 04:21 UTC, carlescufi approved these changes

2021-06-16 06:10 UTC, czeslawmakarski approved these changes

2021-06-16 07:20 UTC, PerMac approved these changes

2021-06-16 08:06 UTC, ioannisg approved these changes

2021-06-16 09:52 UTC, merged