[nrf fromlist] drivers: serial: nrfx_uarte: Add pullups to RXD and CTS
nrfconnect/sdk-zephyr pull request #563
Opened 2021-06-17 12:53 UTC by nordic-krch

Configured UARTE input pins to have pullups. Otherwise when
uart is disconnected pins are floating and generate receiver
errors.

Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/36366

Signed-off-by: Krzysztof Chruscinski <krzysztof.chruscinski@nordicsemi.no>

2021-06-17 14:08 UTC, MarekPorwisz requested changes
similar change needs to be applied in: uarte_nrfx_pins_enable function as it overwrites those settings

2021-06-17 14:35 UTC, MarekPorwisz approved these changes

2021-06-18 07:02 UTC, anangl approved these changes
I think it would be good to also apply the same corrections in `uart_nrfx_uart.c`.

2021-06-18 10:01 UTC, carlescufi approved these changes
This now fixes both uarte and uart

2021-06-18 13:31 UTC, edmont approved these changes

2021-06-18 13:33 UTC, merged