Changes to flash simulator to fit nRF53 DFU
nrfconnect/sdk-zephyr pull request #593
Opened 2021-08-17 07:28 UTC by sigvartmh

Since we are using this for emulating flash in RAM for the nRF53 Dual Core update procedure some changes need to be made to make it more usable. 

*  Removing the stats to save code space
* Make `mock_flash` public so that we can access the address of the RAM region so that it can be passed to `pcd_update`.

2021-08-17 13:35 UTC, nvlsianpu requested changes
Following recent changes to the manual you need to open PR to the upstream with changes to the flash_simulator and make changes here as [fromlist].

2021-08-19 07:18 UTC, sigvartmh commented
Changed to fromlist and PR opened upstream

2021-08-25 12:05 UTC, hakonfam commented on subsys/dfu/boot/CMakeLists.txt
> +if(CONFIG_BOOT_IMAGE_ACCESS_HOOKS)
Why is this here?

2021-09-06 08:20 UTC, hakonfam commented
Superseded by what https://github.com/nrfconnect/sdk-nrf/pull/5439 included

2021-09-06 08:20 UTC, closed without merging