[nrf fromlist] modules: Add TF-M SECURE_UART1 config
nrfconnect/sdk-zephyr pull request #618
Opened 2021-09-09 08:50 UTC by Vge0rge

-This adds a Kconfig configuration which allows
 disabling SECURE_UART1.

Signed-off-by: Georgios Vasilakis <georgios.vasilakis@nordicsemi.no>

2021-09-09 11:42 UTC, oyvindronningstad reviewed
Good to have this! Please reference the upstream PR in the commit message.

2021-09-09 11:42 UTC, oyvindronningstad commented on modules/trusted-firmware-m/CMakeLists.txt
> +	list(APPEND TFM_CMAKE_ARGS -DSECURE_UART1=ON)
Fix alignment

2021-09-15 10:43 UTC, Vge0rge commented on modules/trusted-firmware-m/CMakeLists.txt
> +	list(APPEND TFM_CMAKE_ARGS -DSECURE_UART1=ON)
I will, thanks!

2021-09-15 10:44 UTC, Vge0rge commented
> Good to have this! Please reference the upstream PR in the commit message.

I will indeed, I just wanted to have the first round of the reviews before I do to avoid multiple revisions upstream.

2021-09-20 07:36 UTC, Vge0rge commented on modules/trusted-firmware-m/CMakeLists.txt
> +	list(APPEND TFM_CMAKE_ARGS -DSECURE_UART1=ON)
Should be fixed now :)

2021-09-22 13:31 UTC, tejlmand requested changes
upstream Zephyr doesn't provide a custom `tfm_hal_platform_init` that avoids calling `stdio_init()`.

This means that disabling SECURE_UART1 in Zephyr will lead to a bus fault, hence I can't see how the upstream PR can be approved at current state.

See: https://github.com/zephyrproject-rtos/zephyr/pull/38670#pullrequestreview-760915168

2021-09-22 14:22 UTC, Vge0rge commented
I will do the change only in the sdk-nrf.

2021-09-22 14:22 UTC, closed without merging