[nrf fromlist] doc: cmake package: remove stale cmake version lines
nrfconnect/sdk-zephyr pull request #626
Opened 2021-09-17 15:44 UTC by mbolivar-nordic

Upstream PR:
https://github.com/zephyrproject-rtos/zephyr/pull/38636

This page is meant to document the behavior of the Zephyr cmake
package. However, its example CMake snippets contain some stale
references to a minimum version (3.13.1, now 3.20).

These lines are a bit of a distraction anyway, so just remove them.
They matter in general, but they don't matter where the Zephyr cmake
package is concerned.

Signed-off-by: Martí Bolívar <marti.bolivar@nordicsemi.no>

2021-09-17 16:14 UTC, shantha-14 requested changes
Shouldnt this update cmake_minimum_required to 3.20.5 instead of removing. This bug was actually found by an external who followed the getting started guide and found build errors ?

2021-09-20 18:59 UTC, tejlmand approved these changes

2021-09-20 19:14 UTC, tejlmand commented
> Shouldnt this update cmake_minimum_required to 3.20.5 instead of removing. This bug was actually found by an external who followed the getting started guide and found build errors ?

This is not from the getting started guide, but from the Zephyr CMake package description.
Users should read the guide to understand and be familiar with the Zephyr CMake package but not use it as a reference / template on how to write a CMakeLists.txt file for an application, as it lacks several steps in that regard.

2021-09-20 20:11 UTC, carlescufi approved these changes

2021-09-20 20:14 UTC, mbolivar-nordic commented
Not needed

2021-09-20 20:14 UTC, closed without merging