[nrf noup] linker: only add Sx labels if SECURE_BOOT is enabled
nrfconnect/sdk-zephyr pull request #716
Opened 2022-02-01 11:18 UTC by kapi-no

If CONFIG_SECURE_BOOT is not enabled then these symbols will
not be defined.

Ref: NCSDK-6211

Signed-off-by: Håkon Øye Amundsen <haakon.amundsen@nordicsemi.no>

2022-02-11 18:08 UTC, mbolivar-nordic commented
Please rebase onto the new history in main

2022-03-09 12:43 UTC, tejlmand requested changes
Changes looks good, but please mark the commit  as a `fixup` commit, by having the following line in the commit message (For example line 3 in commit message)
```
fixup! [nrf noup] tree-wide: support NCS Partition Manager (PM) definitions
```

2022-05-02 08:36 UTC, kapi-no commented
Rebased my PR. @tejlmand, I changed the commit description according to your suggestion.

2022-05-10 06:31 UTC, kapi-no commented
Rebased after upmerge. The diff is the same

2022-05-12 08:58 UTC, nvlsianpu approved these changes

2022-05-12 11:39 UTC, rlubos approved these changes

2022-05-12 11:41 UTC, merged