[nrf fromlist] tfm: Add config to disable all TF-M output
nrfconnect/sdk-zephyr pull request #723
Opened 2022-02-03 10:30 UTC by joerchan

Add config to disable all TF-M output. This configuration is needed
in order to exclude the UART driver through a select in Kconfig
when either the code size optimization or the UART instance requires it.

2022-02-09 14:01 UTC, shantha-14 commented
removed milestone for NCS 1.9.0

2022-02-11 18:08 UTC, mbolivar-nordic commented
Please rebase onto the new history in main

2022-02-15 08:35 UTC, tejlmand requested changes
please see: https://github.com/zephyrproject-rtos/zephyr/pull/42444#pullrequestreview-882623321

2022-02-15 15:24 UTC, tejlmand approved these changes

2022-02-18 22:14 UTC, mbolivar-nordic approved these changes

2022-03-24 15:10 UTC, closed without merging