[nrf noup] Bluetooth: BT_L2CAP_ECRED is no longer experimental
nrfconnect/sdk-zephyr pull request #903
Opened 2022-09-02 12:36 UTC by hermabe

BT_L2CAP_ECRED is not marked as experimental upstream and we qualify it
downstream.

To be squashed with 1e8c632358761d97cf2d659eb9fdc316b4558547 in the next
upmerge.

Signed-off-by: Herman Berget <herman.berget@nordicsemi.no>

2022-09-02 12:56 UTC, Thalley approved these changes

2022-09-05 12:49 UTC, carlescufi requested changes
Why not do this upstream? This is a Host feature.

2022-09-05 12:52 UTC, Thalley commented
> Why not do this upstream? This is a Host feature.

It has already been removed upstream. The `select experimental` is only downstream.

2022-09-05 14:09 UTC, carlescufi approved these changes

2022-09-06 09:56 UTC, merged