[nrf noup] samples/mgmt/smp_svr: Add nrf5340dk_nrf5340 support
nrfconnect/sdk-zephyr pull request #909
Opened 2022-09-13 12:10 UTC by de-nordic

Add nrf5340dk_nrf5340 board specific configuration that allows for APP and NET updates.

NCSDK-16882

Signed-off-by: Dominik Ermel <dominik.ermel@nordicsemi.no>

2022-09-13 13:09 UTC, joan-nordic approved these changes

2022-09-16 09:44 UTC, gopiotr commented
In case of problems with Jenkins CI for the future, please rebase your PR branch to the newest `sdk-zephyr` main, due to the significant changes in CI process, which requires the newest version of `sdk-zephyr` main (especially this commit: https://github.com/nrfconnect/sdk-zephyr/commit/a1b281e16961fcfd04fbb6bb691dd1ee4d0123bf). Sorry for the inconvenience.

2022-09-19 16:15 UTC, carlescufi requested changes
Why is this downstream? cc @de-nordic @nordicjm

2022-09-27 10:37 UTC, de-nordic commented
> Why is this downstream? cc @de-nordic @nordicjm

Because this is partition manager enabled configuration to allow our customers to build smp_svr sample for nrf5340dk with APP/NET CPU update capabilities.

2023-03-17 16:33 UTC, jfischer-no commented
Still relevant or can it be closed?

2023-03-29 15:57 UTC, de-nordic commented
Converting to draft as this is currently broken due to problems with LittleFS. When LIttlefs and file system group gets disabled this works fine.

2025-03-11 14:45 UTC, nvlsianpu commented
@de-nordic This was superseded by https://github.com/nrfconnect/sdk-zephyr/pull/2269
So I'm closing this.
Reopen If I'm wrong.

2025-03-11 14:45 UTC, closed without merging