[nrf noup] bluetooth: increase discaradable buffer size
nrfconnect/sdk-zephyr pull request #939
Opened 2022-10-21 12:09 UTC by martintv

Make discaradable buffer size fit extended adv reports that has only received legacy adv pdus.

Signed-off-by: Martin Tverdal <martin.tverdal@nordicsemi.no>

2022-10-24 08:10 UTC, Thalley requested changes
Are extended advertising reports even discardable in the first place? 

In Zephyr they are not, because that would make it impossible to support reassembly of long advertising packets.

2022-10-24 08:27 UTC, rugeGerritsen approved these changes

2022-10-24 09:18 UTC, martintv commented
> Are extended advertising reports even discardable in the first place?
> 
> In Zephyr they are not, because that would make it impossible to support reassembly of long advertising packets.

Sorry, should have written better description for this one. I intend to make extended adv reports that only contain legacy data inn them (they where received as ADV_IND pdus entirely) as discardable https://github.com/nrfconnect/sdk-nrf/pull/9072

First this is intended to go into NCS 2.1.x... might fix it in a different way on main

2022-10-24 11:41 UTC, Thalley commented
> > Are extended advertising reports even discardable in the first place?
> > In Zephyr they are not, because that would make it impossible to support reassembly of long advertising packets.
> 
> Sorry, should have written better description for this one. I intend to make extended adv reports that only contain legacy data inn them (they where received as ADV_IND pdus entirely) as discardable [nrfconnect/sdk-nrf#9072](https://github.com/nrfconnect/sdk-nrf/pull/9072)
> 
> First this is intended to go into NCS 2.1.x... might fix it in a different way on main

That makes more sense :)

2022-10-24 11:41 UTC, Thalley approved these changes

2022-10-26 12:25 UTC, PerMac commented
@gopiotr Is this the issue with quarantine and versioning we had with backporting?

2022-10-26 14:16 UTC, gopiotr commented
> @gopiotr Is CI/Jenkins/ZEPHYR failure the issue with quarantine and versioning we had with backporting?

Yes, exactly, that is why CI failed. I already introduced change into Jenkinsfile to solve this problem:
https://github.com/nrfconnect/sdk-zephyr/commit/56d8a4f56fb6de6cf2494af1b38aca168484b6cb

@martintv please rebase this PR to the newest commit in `v3.1.99-ncs1-branch` branch and that should solve problem with CI. Sorry for the inconvenience.

2022-10-27 08:27 UTC, rlubos commented
@martintv Can you please rebase the PR as suggested above?

2022-10-27 12:41 UTC, merged